### ISSUE TITLE
Use all default emoji files in addition to a custom csv

### ISSUE THREAD

**Issue by slavistan** [fdw/rofimoji#101]
Hi!

Is there a way to use the `--files all` option and add another custom file on top? Neither command-line arguments nor the configuration file seem to support this.

The `files = [all, ~/.config/rofimoji/custom-emojis.csv]` setting as well as the `--files all ~/.config/rofimoji/custom-emojis.csv` command-line option cause the error `FileNotFoundError: Couldn't find file 'all'`. 

Any way to achieve that without having to explicitly list all default .csv-files?

Thanks 🙂

**Comment by fdw** [comment]
This should be fixed now 🙂

**Comment by slavistan** [comment]
Cool :) I'll check it out once it's in the repositories. Thank you!

**Comment by fdw** [comment]
Be warned, there is no release yet and the next one might take a while.

I'll close this issue for now. If you have any problems with it, feel free to re-open 🙂

**Comment by slavistan** [comment]
Na, go ahead, that's fine. Thanks a lot for the quick reply 🙂
