### ISSUE TITLE
The forced use of the option `markup-rows` makes it impossible to search for the symbol '<'

### ISSUE THREAD

**Issue by chmduquesne** [fdw/rofimoji#103]
Hi,

I use rofimoji with custom files, because I like to customize the "shortcuts". For example, instead of using [superscripts_and_subscripts.csv](https://github.com/fdw/rofimoji/blob/main/src/picker/data/superscripts_and_subscripts.csv), I am using my own version, where

```csv
₁ Subscript One
```
becomes
```
₁ _1
```
The reason for this is that I find it orders of magnitude more intuitive to look for `_1` than `Subscript One`. For similar reasons, I also defined shortcuts to mathematical symbols to their latex equivalent.

I would love to use a similar approach to look for symbols like ← or →, and type text like `<-` or `->` to look for arrows. However, because the option `markup-rows` is used, rofi does not let me look for the symbol `<`.

I would like to suggest to make the use of this option optional, in order to make the search more user friendly. I personally don't care too much for the `<small></small>` style which often accompanies the description, so I would edit my files to remove this styling, because it makes searching much easier.

Cheers,
Christophe-Marie

**Comment by chmduquesne** [comment]
So, to summarize the issue:

I would like to change the text description of arrow characters to
```
← <-
→ ->
⇐ <=
⇒ =>
```
because it is easier to remember and faster than searching for "leftwards arrow". Currently, because rofi tries to show text as markup, it ignores the characters `<` and `>` in the search, which makes using such descriptions impossible. I am open to any solution.

Cheers,
Christophe-Marie

**Comment by fdw** [comment]
I haven't forgotten this issue, it's just that I see no real solution (so far). I like the styled descriptions to reduce the clutter of the keywords a bit. However, there seems to be no way to have both that and having `>` searchable in `rofi`.

Maybe some trickery to do away with `-markup-rows` if the items do not contain tags?

**Comment by fdw** [comment]
I think I finally found a solution for you, @chmduquesne: Can you please try to escape the angle brackets with `&lt` and `&gt`? This seems to work for me 🙂

**Comment by chmduquesne** [comment]
It works! Fantastic 😊
