### ISSUE TITLE
Multiple data files in rofimoji.rc

### ISSUE THREAD

**Issue by dithpri** [fdw/rofimoji#105]
Not really an issue with rofimoji, but with how the `ConfigArgParse` library handles things.
There's no wiki, so I'm opening an issue in case anyone has the same problem and is looking for a solution.
<hr>

If you want to specify multiple files to read characters from, in `rofimoji.rc`, the syntax is (a bit counterintuitively):
```
files=[file1,file2,file3]
```
So, for example:
```
files=[emojis,math,box_drawing]
```
See also: [ConfigArgParse#110](https://github.com/bw2/ConfigArgParse/issues/110)

Edit: Apologies, I couldn't find the solution in docs, but a similar example appears in the repo's README. I think it would be beneficial to also include it in the man page.

**Comment by fdw** [comment]
Thanks, I've added a bit to the man page. Hope that helps 🙂
