### ISSUE TITLE
Problem with dependencies

### ISSUE THREAD

**Issue by EliasTheDev** [fdw/rofimoji#108]
* OS: Arch Linux
* Windows Manager: i3wm
* Error: `Could not find a valid way to type characters. Please check the required dependencies.`

* Any ideas why this problem is occurring? Thanks

**Comment by fdw** [comment]
Could it be that you're missing `xdotool` (if you're on X11)?

**Comment by EliasTheDev** [comment]
Even after installing `xdotool`, the error is still occurring. Perhaps it could be some corrupt files problem?

**Comment by fdw** [comment]
Since you're on i3, I think you're also on X11, right? Do you have an environment variable called `WAYLAND_DISPLAY`? Does copying the character work, or do you get a similar error?

**Comment by EliasTheDev** [comment]
1 * Yes, I am - indeed - on X11
2 * No, I do not have an environment variable called `WAYLAND_DISPLAY`
3 * Unfortunately, I can't open the program, it only gives me that error

**Comment by fdw** [comment]
> Unfortunately, I can't open the program, it only gives me that error

It does that right at the start, before `rofi` even opens? That is strange...
How do you start `rofimoji`?

**Comment by EliasTheDev** [comment]
Oh mine, the problem was basically that `rofi` wasn't installed on my machine, that was the problem from the beginning. Thank you so much for your time and kindness! And sorry for my stupidity. 😄

**Comment by fdw** [comment]
No worries, we've all done stuff like this before 😉

Hope you have fun with `rofimoji` 🙂
