### ISSUE TITLE
Option to remove emoji counter

### ISSUE THREAD

**Issue by Celibistrial** [fdw/rofimoji#115]
I use this [theme](https://github.com/catppuccin/rofi) for rofi
![image](https://user-images.githubusercontent.com/82810795/160320511-5492fe7c-d112-4714-9242-be1ea3d4c005.png)

but when this theme is used with rofimoji 
![image](https://user-images.githubusercontent.com/82810795/160320223-9d773c27-2adb-4a2f-97b6-e9e60fb54a01.png)

**Comment by fdw** [comment]
Does `--max-recent 0` already do want you want?

**Comment by Celibistrial** [comment]
Thanks
