### ISSUE TITLE
Can't paste/type automatically in Wayland

### ISSUE THREAD

**Issue by major** [fdw/rofimoji#118]
Howdy! I am using swaywm on Wayland full-time now and rofimoji works there, but it doesn't auto-paste characters as it does under X. Here's my workflow:

- Press hotkey combo to load rofimoji 🚀
- Find my favorite emoji 🥰
- Press enter on my favorite emoji 🎉
- Emoji goes into the clipboard 📋
- Emoji is not pasted into the text box in my browser 😱

I've tried various incantations of `--clipboarder`, `--typer` and `--action`, but I can't seem to get it right. I'm using rofimoji to copy emojis into the clipboard now and then I follow that with a `CTRL-v` to manually paste them.

Does anyone have a configuration that works or a recommendation of how to debug it?

**Comment by fdw** [comment]
Just to make sure I understand: You set the insertion method to `clipboard`, and the emoji is successfully copied to the clipboard, but not inserted from there?
The insertion itself should be triggered with `wtype -M shift -P insert -p insert -m shift`. Does that make sense? Does that work if you do it by hand?

**Comment by major** [comment]
Here's what I'm using right now:

```
rofimoji --action clipboard --skin-tone light --selector-args='-theme solarized -font "monospace 12" -width 800'
```
If I am using this to paste into a terminal, everything works. I launch rofimoji, pick an emoji, press enter, and suddenly the emoji appears in the terminal with no additional keystrokes.

However, if I try this in a Firefox, Thunderbird, or Electron app (Discord/Slack), nothing is pasted.

**Comment by major** [comment]
@fdw Oh boy, ignore me. I just realized Fedora is stuck on wtype 0.3, but 0.4 has been out since January 2022. 🤦🏻‍♂️

I'll work with the package maintainer to get it updated. wtype 0.4 works just fine with rofimoji.

**Comment by fdw** [comment]
That was easier than expected 😄

**Comment by major** [comment]
@fdw For what it's worth, with wtype 0.4, this works solidly in terminals and in firefox when called via a sway hotkey:

```shell
#!/bin/bash

MONITOR_ID=XWAYLAND$(swaymsg -t get_outputs | jq '[.[].focused] | index(true)')
rofimoji --action type --skin-tone light --selector-args="-theme solarized -font 'Hack 12' -width 800 -monitor ${MONITOR_ID}"
```

It's not working in electron apps (Discord, Slack), but I think there's a separate issue there.

**Comment by adament** [comment]
I created two hotkeys, one with --typer wtype and another with --typer xdotool and then I use the xdotool hotkey for XWayland applications. Not the best user experience but it seems to work for most applications including some electron apps.

**Comment by fdw** [comment]
If you have an idea how to improve the experience, I'm interested 🙂

**Comment by major** [comment]
I'm still trying to figure it out. 🤔 https://major.io/2022/05/27/efficient-emoji-experience-in-wayland/

**Comment by fdw** [comment]
So, I had a weird idea: First, is it possible for `wtype`, `wl-clipboard` etc to know the currently active window (similar to `xdotool getactivewindow getwindowclassname`)?

If so, how about you can configure default actions in `rofimoji` per window class? That would add more complexity, and the config would probably have to be maintained. But it could be quite nice for users, and hopefully the config doesn't change often.

**Comment by major** [comment]
> I had a (short) look around, but it seems that there is no way to get the class of the active window in Wayland, right? That makes my suggestion above impossible confused

I haven't found a way to do that either. I use sway and everything seems to be focused on outputs (like a display/workspace) as opposed to individual windows.

**Comment by adament** [comment]
This is unfortunately not pure wayland but for sway this seems to work for me:
```bash
!/bin/sh
shell=$(swaymsg -t get_tree | jq 'recurse(.nodes[]) | select(.focused == true).shell')
typer="wtype" && [[ $shell == '"xwayland"' ]] && typer="xdotool"
rofimoji --action type --typer $typer
```
Please excuse my poor shell scripting skills.
