### ISSUE TITLE
ADD Select All (Ctrl+A or Command+A) 

### ISSUE THREAD

**Issue by allanlaal** [fdw/rofimoji#119]
## use case

I  search for "nature"
I find nothing
I `Ctrl+A` to select my search and overwrite it

currently does nothing, which was a dealbreaker for me :(

**Comment by fdw** [comment]
Sorry to hear that 🙁

`rofimoji` relies on `rofi` (or `wofi` on Wayland) for that functionality, so there's not much I can change. Maybe you can find something in [`rofi`s documentation](https://github.com/davatorium/rofi/blob/next/doc/rofi-keys.5.markdown) to help you. You can pass these parameters using `--selector-args`.
