### ISSUE TITLE
ADD Zoom (Ctrl+MouseScroll / Command+MouseSroll)

### ISSUE THREAD

**Issue by allanlaal** [fdw/rofimoji#120]
screens too big, emoji picker selection too small for me. Zooming in & out would be awesome

**Comment by allanlaal** [comment]
bonus: remembers zoom

**Comment by fdw** [comment]
Again, `rofimoji` uses `rofi` and `wofi` for the actual menu. But if you're on a HiDPI screen and use `rofi`, you can try [setting the dpi](https://github.com/davatorium/rofi/blob/next/doc/rofi.1.markdown#configuration) to a better value. I use `192`, for example.
