### ISSUE TITLE
`emojiextractor.py` references `copyme.py`

### ISSUE THREAD

**Issue by owenthewizard** [fdw/rofimoji#122]
~~Not sure if this is correct...
https://github.com/fdw/rofimoji/blob/main/src/extractors/emojiextractor.py#L112
It seems to me it should be `emojis.csv`.~~

<sup>I really want to rewrite this in Rust...</sup>

**Comment by owenthewizard** [comment]
I just realized I entirely misread `emojiextractor.py`. Nevermind this...

**Comment by fdw** [comment]
Yep, that one is special 😉

> I really want to rewrite this in Rust...

I'd be curious what it looks like 🙂 But I think having the extractors in Python is easier for new contributions.
