### ISSUE TITLE
Rofimoji crashed and now won't start

### ISSUE THREAD

**Issue by zkwinkle** [fdw/rofimoji#124]
I have a keybind to execute the following command: `rofimoji -s neutral -a clipboard --keybinding-copy Ctrl+c --max-recent 0`. I tried copying the Eyes emoji, after that I tried opening rofimoji again but it wouldn't, executing the previous command from the terminal (or also executing rofimoji with any other or no flags) only crashes and gives the following traceback:

```
Traceback (most recent call last):
  File "/usr/bin/rofimoji", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/picker/rofimoji.py", line 508, in main
    Rofimoji().standalone()
  File "/usr/lib/python3.10/site-packages/picker/rofimoji.py", line 224, in standalone
    returncode, stdout = self.open_main_rofi_window()
  File "/usr/lib/python3.10/site-packages/picker/rofimoji.py", line 356, in open_main_rofi_window
    self.read_character_files(),
  File "/usr/lib/python3.10/site-packages/picker/rofimoji.py", line 296, in read_character_files
    for character in self.read_frecencies().keys():
  File "/usr/lib/python3.10/site-packages/picker/rofimoji.py", line 448, in read_frecencies
    (frecency, character) = line.strip().split(' ')
ValueError: not enough values to unpack (expected 2, got 1)
```

I tried uninstalling and reinstalling to no avail. Haven't tried just restarting my copmuter yet but I wanted to do the bug report while I still had the traceback in my terminal. Gonna report if a simple restart fixes the issue.

**Comment by zkwinkle** [comment]
Okay I figured out how to fix the problem. The old restart didn't help so I started debugging. Added the following print in the for loop the problem was happening
```
with frecency_file_location.open('r') as file:
    for line in file:
        print("Line:", line)
        (frecency, character) = line.strip().split(' ')
        frecencies[character] = int(frecency)
```
And got the following output:
```
Line: 71 👀

Line: 41 😔

Line: 39 😭

Line: 28 🧑

Line: 20 😎

Line: 19 😳

Line: 16 🤧

Line: 13 🥺

Line: 12 😈

Line: 9 🙁

Line: 8 🥹

Line: 7 🤔

Line: 6 🥰

Line: 6 🤓

Line: 6 🥴

Line: 6 💀

Line: 6 🥵

Line: 5 😡

Line: 5 😅

Line: 4 🙃

Line: 4 😤

Line: 4 😂

Line: 4 🤣

Line: 4 🤠

Line: 4 🤯

Line: 3 👈

Line: 3 👉

Line: 3 🤢

Line: 3 🤨

Line: 3 ™

Line: 3 🤦

Line: 3 😠

Line: 3 🐸

Line: 2 ✨

Line: 2 🤞

Line: 2 😏

Line: 2 🤪

Line: 2 🥳

Line: 2 😢

Line: 2 🧔

Line: 1 

Traceback (most recent call last):
  File "/usr/bin/rofimoji", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/picker/rofimoji.py", line 510, in main
    Rofimoji().standalone()
  File "/usr/lib/python3.10/site-packages/picker/rofimoji.py", line 224, in standalone
    returncode, stdout = self.open_main_rofi_window()
  File "/usr/lib/python3.10/site-packages/picker/rofimoji.py", line 356, in open_main_rofi_window
    self.read_character_files(),
  File "/usr/lib/python3.10/site-packages/picker/rofimoji.py", line 296, in read_character_files
    for character in self.read_frecencies().keys():
  File "/usr/lib/python3.10/site-packages/picker/rofimoji.py", line 450, in read_frecencies
    (frecency, character) = line.strip().split(' ')
ValueError: not enough values to unpack (expected 2, got 1)
```
So then I printed the `frecency_file_location` to figure out where this file was. Inside it, found the line that was just a "1" with no emoji to it's right and deleted it, now rofimoji is back in business!

Don't know if I should close the issue so I'll leave it open as a bug report, maybe the ValueError could be caught and the buggy line deleted if this happens?

**Comment by zkwinkle** [comment]
Sorry for the spam, accidentally closed the issue after saying I wouldn't 😭

**Comment by zkwinkle** [comment]
Sorry for the spam, accidentally closed the issue after saying I wouldn't 😭

**Comment by fdw** [comment]
No worries, and thanks for the bug report!

I'm not sure if I want to catch that error - while it would have solved your error, it's just pasting over the problem that something weird happened in that file. I'd rather find out why that entry wasn't written correctly, but I don't suppose you remember how that came about?

**Comment by zkwinkle** [comment]
Well I'm not 100% certain this was the cause, but it happened after I tried copying an emoji with my Ctrl+c keybind. I cannot reproduce the bug though. :/

**Comment by fdw** [comment]
Yes, for some reason, the file contained one line with just a frecency but no character. This arose when you copied the 👀, but that's quite likely not the reason.

I can only imagine one possible cause: Have you ever used some whitespace character and use the latest stable version? It has has bug with exactly this scenario.

**Comment by fdw** [comment]
Since this should already be fixed on `main`, I've decided to push out a new release. Can you please re-open the ticket if it isn't?
