### ISSUE TITLE
Unicode Decode error when attempting to load OpenMoji

### ISSUE THREAD

**Issue by DeeeeLAN** [fdw/rofimoji#125]
I installed OpenMoji from the AUR, then ran the following:
```bash
rofimoji --files=/usr/share/fonts/openmoji/OpenMoji-Color.ttf
```

Which resulted in the following stacktrace:
```bash
Traceback (most recent call last):
  File "/usr/bin/rofimoji", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/picker/__main__.py", line 12, in main
    Rofimoji().standalone()
  File "/usr/lib/python3.10/site-packages/picker/rofimoji.py", line 217, in standalone
    action, value = self.open_main_rofi_window()
  File "/usr/lib/python3.10/site-packages/picker/rofimoji.py", line 350, in open_main_rofi_window
    self.read_character_files(),
  File "/usr/lib/python3.10/site-packages/picker/rofimoji.py", line 294, in read_character_files
    characters_from_file = self.load_from_file(file)
  File "/usr/lib/python3.10/site-packages/picker/rofimoji.py", line 334, in load_from_file
    return file.read_text().strip('\n').split('\n')
  File "/usr/lib/python3.10/pathlib.py", line 1135, in read_text
    return f.read()
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 16: invalid start byte
```

I am running rofimoji 5.5.0 installed through Pacman.

**Comment by fdw** [comment]
I'm not sure what you're trying to do, sorry: You pass a font file where `rofimoji` expects a description of characters.

Do you want to use OpenMoji as a font in `rofi`? Then you can either configure it that way (for example with `--selector-args "-font OpenMoji"`, or you can try to use OpenMoji as the emoji font on your whole system. That might already work after you installed them.

**Comment by DeeeeLAN** [comment]
Ah, I guess I didn't understand the documentation then, since `--files` makes me think it is looking for font files rather than character sets. 

Anyway, When I try 
```bash
rofimoji --files=emojis --selector-args="-font OpenMoji"
```
I get the following:
![rofi-2022-08-23-1431-00000](https://user-images.githubusercontent.com/12877032/186270671-847262b0-a46e-4223-8821-3153de044eb3.png)

I tried setting the `~/.config/fontconfig/fonts.conf` file as was mentioned in some similar previous issues, but either I have the wrong syntax, or that is just not working.

**Comment by fdw** [comment]
If you list your fonts with `fc-list`, does OpenMoji turn up? What's the exact name (try using that for `--selector-args`).
Does OpenMoji work in other applications?

**Comment by DeeeeLAN** [comment]
`fc-list` gives the following:
```bash
> fc-list | grep openmoji
/usr/share/fonts/openmoji/OpenMoji-Black.ttf: OpenMoji:style=Black
/usr/share/fonts/openmoji/OpenMoji-Color.ttf: OpenMoji:style=Color
```

All of the following had the same results as the above screenshot:
```bash
rofimoji --files=emojis --selector-args="-font OpenMoji"
rofimoji --files=emojis --selector-args="-font OpenMoji-Black"
rofimoji --files=emojis --selector-args="-font OpenMoji Black"
rofimoji --files=emojis --selector-args="-font OpenMoji-Color"
rofimoji --files=emojis --selector-args="-font OpenMoji Color"
```

I tried installing the joypixels font and I think I figured out the issue. Apparently openmoji is an OTF not TTF font. So I am going to close this ticket. 

When I launch rofimoji from the bin directly, those boxes still show up, but the emoji is between the box and the word as expected. When I launch rofimoji from rofi, the boxes are no longer visible. I don't intend to launch it directly and it might just be due to how my custom theme is getting interpreted, so I am not concerned too much about that.

**Comment by fdw** [comment]
Glad that it works for you now 🙂

> Apparently openmoji is an OTF not TTF font.

According to the filename, it is actually a `ttf` font - is it misnamed? Apart from that, `rofi` should be able to deal with OTF as well. It could also be that I misremembered the exact parameter for `rofi`...

> When I launch rofimoji from the bin directly, those boxes still show up, but the emoji is between the box and the word as expected.

Ah, I thought the boxes were artifacts of the emoji. But I guess your theme asks for icons? `rofimoji` doesn't have icons, so there won't be any.
