### ISSUE TITLE
[Font Problem] Weird characters appear before emojis

### ISSUE THREAD

**Issue by karx1** [fdw/rofimoji#127]
* What does rofimoji show instead of the emojis? Can you please share a screenshot (`Alt+Shift+s** in rofimoji)

![image](https://user-images.githubusercontent.com/49726028/187236013-9a7c464f-431f-413f-9971-33fe31a518d4.png)

* What do other apps like Firefox/Chrome/your text editor show instead of emojis?
    * Just the emoji, no square
* Which emoji fonts do you have installed?
    * ttf-twemoji
* Are the emoji fonts set in your font config?
    * No, but this used to work fine until the latest update
* Which versions of rofimoji and pango are installed?
    * pango 1:1.50.9-1 and rofimoji 5.5.0-1 (Arch Linux)

**Comment by fdw** [comment]
Could it be that your `rofi` theme uses icons? Or do you use a custom file?

**Comment by karx1** [comment]
My rofi theme doesn't use icons, the squares don't show up when I launch rofi to open an app. Adding `-no-show-icons` to the selector-args in rofimoji doesn't do anything either.
Yash Karandikar
d5c4 1cbc 071b 41b3 f235 da13 f01e 92cd 2390 f369

Aug 29, 2022 12:16:44 PM Fabian Winter ***@***.***>:

**Comment by fdw** [comment]
Thanks 🙂 Another idea: Which font do you use for text? And could you please paste your `rofi` configuration?

Also. which update broke it? `rofimoji`? Something else?

**Comment by karx1** [comment]
Hi, I use the Cascadia Code font, but I don't think that's the issue because I tried it with a couple of other fonts and the issue remains.

I updated rofi and rofimoji at the same time, so I'm not sure which update it was that broke it exactly.

**Comment by fdw** [comment]
Could you please add your `rofi` configuration and theme?

**Comment by fdw** [comment]
Thanks. I've tried your theme, but it works fine for me. Also on latest `rofi` and `rofimoji`.

I'm grasping for straws, but what's your Python version?

**Comment by karx1** [comment]
My python version is Python 3.10.6, and it was updated at the same time as rofi and rofimoji.

**Comment by karx1** [comment]
So I downgraded rofi to 1.7.3-1, and now the squares don't show up. This seems to be an issue with rofi and not rofimoji

**Comment by fdw** [comment]
Thanks for that testing! I don't see what `rofimoji` could do differently to fix that.

Have you opened a bug against `rofi`?

**Comment by MosaicMan** [comment]
I was having the same issue in Arch Linux. For some reason, running it as a rofi mode does not show the weird squares before the emoji:

`rofi -show emoji -modi emoji:/usr/bin/rofimoji`

**Comment by alpheratz0** [comment]
Hi, I git bisect'd rofi and found that this behavior was introduced in the
following commit of rofi: https://github.com/davatorium/rofi/commit/be6fe8ac.
It replaced the dot indicator with a checkbox (those weird characters) when
the -multi-select option of rofi-dmenu is passed, you cannot disable that
directly from rofimoji because it doesn't have an option to just pick a single
emoji and it always starts rofi-dmenu with the `-multi-select` option enabled.

**Comment by fdw** [comment]
Thanks for the work, @alpheratz0! That explains a lot.
I'd like to work on the issue, but I currently cannot reproduce it as my `rofi` is too old. Please be patient 🙂

> However, (on my system) using that command no longer inserts the emoji into the application like running rofimoji does. Any ideas?

This is a [known limitation of the script mode](https://github.com/fdw/rofimoji#caveats-when-running-rofimoji-as-a-rofi-mode), sorry.

**Comment by alpheratz0** [comment]
> Thanks for the work, @alpheratz0! That explains a lot. I'd like to work on the issue, but I currently cannot reproduce it as my `rofi` is too old. Please be patient slightly_smiling_face

It's not a big problem, I can wait 😆

Cheers!

**Comment by fdw** [comment]
I've just pushed something that should help with this problem. Please try it and report back!
If it works, I'll push out a release in the next days.

**Comment by karx1** [comment]
The new commit works for me on rofi 1.7.5, the squares no longer show up.

**Comment by fdw** [comment]
Release is out 🙂
