### ISSUE TITLE
Because of emoji loading delay, incorrect layout appears for a split second when opening rofimoji.

### ISSUE THREAD

**Issue by Asmageddon** [fdw/rofimoji#129]
I noticed this when I decided that I want a denser layout for rofimoji, and set columns to 8.

However, rofimoji first renders before it has loaded all the characters to display - in my case, first rendering 25 characters, which isn't enough to render 8 columns, and renders 2 instead.

This causes flickering and is undesirable.

**Comment by fdw** [comment]
This is in `rofi`'s domain. Which version of `rofi` do you use?

**Comment by Asmageddon** [comment]
1.7.3. I managed to address this by adding `fixed-columns: true;` under the `listview` section in a rofimoji config, but it's still frustrating.

**Comment by Asmageddon** [comment]
Just upgraded to 1.7.5, where the issue does not appear to be present. Whoops.

**Comment by Asmageddon** [comment]
Yes indeed :P
