### ISSUE TITLE
[FR] Allow multiple character lists to be specified as separate modi

### ISSUE THREAD

**Issue by Asmageddon** [fdw/rofimoji#130]
For example, I'd like to have Unicode character search in addition to the emoji view, without having to load all tables and pollute the emoji search.

**Comment by fdw** [comment]
Sorry, I'm not sure what you mean. Do you want to use `rofimoji` multiple times as a `rofi` mode? If so, that should already be possible.

**Comment by Asmageddon** [comment]
I mean using rofimoji itself, since some of its features don't work when using it as a rofi mode, and I want to have it on a separate keybinding anyway.

**Comment by fdw** [comment]
Okay... you want to search through all of Unicode, but show only emojis at first? Did I get that right?

Unfortunately, I don't think that's possible. You can specify emoji first, for example `files = [emoji, braille, arabic]` to show emoji first. But I don't think `rofi` can dynamically load more entries in `dmenu` mode.

**Comment by Asmageddon** [comment]
I was thinking about having separate tabs as separate modi, e.g. "emoji" and "unicode" mode.

**Comment by fdw** [comment]
Ah, I see. Not sure if that is possible, but I'll have a look 🙂

**Comment by fdw** [comment]
It seems that you cannot have tabs in `rofi` when using the dmenu mode (which `rofimoji` uses). One alternative would be to use `rofimoji` as a rofi mode, but then you [lose some capabilities](https://github.com/fdw/rofimoji/blob/main/README.md#caveats-when-running-rofimoji-as-a-rofi-mode).

Would something like the file selector described in #126 help? Or can you describe in more detail what annoys you when you just have everything in one go?

**Comment by Asmageddon** [comment]
I personally wouldn't be satisfied with it.

Most of the time, I just want to paste an emoji in, and don't need any other characters polluting the menus, and I don't want to need an extra keypress for the default usecase.

It's not a high priority issue, it'd just be nice to be able to paste in or look up arbitrary Unicode in a convenient way.

**Comment by fdw** [comment]
After having looked at this, I unfortunately haven't found a (sensible) way to dynamically fetch more characters into `rofi` or to use modi in `dmenu` mode, sorry.

Not-quite-as-comfortable-but-working solutions would be a second config on a different shortcut, or loading the relevant files for you in a reasonable order. Also, the characters are ordered by frecency, so after some time, your most used should be first.

**Comment by Asmageddon** [comment]
Understandable, thanks for considering my proposal and communicating well :)
