### ISSUE TITLE
Grid Layout

### ISSUE THREAD

**Issue by niksingh710** [fdw/rofimoji#133]
How can i have grid layout that only shows emoji?

**Comment by fdw** [comment]
You can specify which symbols to show using `--files`. The default is to show only emojis.

Regarding the layout, you can use `--selector-args=""` to pass arguments to `rofi` (assuming you use that).

Does that help?

**Comment by niksingh710** [comment]
i want something like this.
![image](https://user-images.githubusercontent.com/60490474/196046518-c954365b-4950-4d19-9a7c-8286355a19a0.png)

**Comment by fdw** [comment]
In your example, the characters are used shown as icons, with the descriptions underneath. I don't think that will ever be possible. One could think about only showing the character with the text hidden (but still searchable), if `rofi` allows this.

In general, though, you can define your own `rofi` theme and use that for `rofimoji`. Up till now, there is none packaged with `rofimoji`, but I'd be open if someone opens a PR.

**Comment by fdw** [comment]
> One could think about only showing the character with the text hidden (but still searchable), if rofi allows this.

Turns out, this is supported by `rofi` 🥳 (Thanks also to @DaveDavenport for his help and the awesome features in `rofi`)

So now I've added support to just show the characters without descriptions, and an example `rofi` theme that may help you define your own. Please try it out 🙂

**Comment by fdw** [comment]
I think we can close this...

**Comment by niksingh710** [comment]
@fdw Sorry mate kindda got between some work.
![image](https://user-images.githubusercontent.com/60490474/221423249-235ab64b-162f-4d0f-bcf9-4c155b89860d.png)
Thankyou the options work really fine.
i got it working something like this.
