### ISSUE TITLE
Absolute paths with `--files` no longer supported in 6.0.0

### ISSUE THREAD

**Issue by igemnace** [fdw/rofimoji#134]
I typically run rofimoji in the following way:

```
data_dir=/usr/lib/python3.10/site-packages/picker/data

rofimoji --action clipboard -f "$data_dir"/{emojis.csv,latin-1_supplement.csv,general_punctuation.csv,math.csv}
```

which allows me to pick from the files already distributed with rofimoji. In 6.0.0, I get the following trace:

```
Traceback (most recent call last):
  File "/usr/bin/rofimoji", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/picker/__main__.py", line 9, in main
    StandaloneRofimoji().standalone()
  File "/usr/lib/python3.10/site-packages/picker/standalone.py", line 25, in standalone
    action, value = self.__open_main_selector_window()
  File "/usr/lib/python3.10/site-packages/picker/standalone.py", line 46, in __open_main_selector_window
    read_characters_from_files(self.args.files, load_frecent_characters(), self.args.use_additional)
  File "/usr/lib/python3.10/site-packages/picker/file_loader.py", line 14, in read_characters_from_files
    for file in __resolve_all_filenames(files, use_additional):
  File "/usr/lib/python3.10/site-packages/picker/file_loader.py", line 26, in __resolve_all_filenames
    resolved_file_names += __resolve_filename(file_name, use_additional)
  File "/usr/lib/python3.10/site-packages/picker/file_loader.py", line 40, in __resolve_filename
    for file in (Path(__file__).parent / "data").glob(file_name if "*" in file_name else file_name + "*"):
  File "/usr/lib/python3.10/pathlib.py", line 1032, in glob
    raise NotImplementedError("Non-relative patterns are unsupported")
NotImplementedError: Non-relative patterns are unsupported
```

Which looks to me like a direct consequence of globbing on `--files` input with `glob`.

Is this intended? That's technically one way of dealing with this: users should no longer use absolute paths with `--files` -- which I'm fine with, would just like to see in the documentation how to address the files, as it isn't obvious to me (`data/emojis.csv` with or without some combination of `../` didn't work for me).

If not otherwise intended, perhaps it should do the trick to just not glob by default if no glob pattern is given by the user?

**Comment by fdw** [comment]
You've found a really interesting scenario there 😉 Let me unpack:
First, you use the packaged files, but with the absolute path (it should be fine to just call `--files latin-1_supplement` etc, without the path and the extension). Secondly, `emojis.csv` was split up for this release into, for example, `emojis_smileys_emotion.csv`. If you had called just `emojis`, it would still work thanks to some backwards-compatible globbing.
And finally, there's the actual bug where `rofimoji` tries to glob in a specific directory for a pattern with an absolute path - which doesn't make any sense.

So, I would recommend you don't use the absolute path for packaged files anymore, and you should think about whether you want all emojis or not. One possible solution is `--files emojis latin-1_supplement general_punctuation math`. That should already fix it for you 🙂

And I'll have a look at the code and improve the error message. Also, do have a suggestion how to make it clearer in the readme that you can use just the file stem for `--files`?

**Comment by igemnace** [comment]
Excellent! Thanks much

Either improve the error message yeah, or I'd wager a descriptive example in the man page would do really well here.

E.g.

```
       --files=FILE [FILE ...], -f FILE [FILE ...]
              Read  characters  from  this  file  instead, one entry per line In the config file, several files need to be listed as
              files=[_FILE_, _FILE_ ]. For example: --files=emojis latin-1_supplement general-punctuation math

              See the distributed data directory for a list of filenames you can use by default.
```

**Comment by fdw** [comment]
I've added some lines to the manpage and the readme, and fixed the globbing bug 🙂

If it works for you now, I'll close the issue.

**Comment by latipun7** [comment]
I have `~/.config/rofimoji.rc`:
```
files = [emojis, nerd_font, arrows, ~/.local/share/rofimoji/latipun.csv]
skin-tone = neutral
```

It works on v5.6.0, but has this error on v6.0.0:
```sh
❯ rofimoji
Traceback (most recent call last):
  File "/usr/bin/rofimoji", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/picker/__main__.py", line 9, in main
    StandaloneRofimoji().standalone()
  File "/usr/lib/python3.10/site-packages/picker/standalone.py", line 25, in standalone
    action, value = self.__open_main_selector_window()
  File "/usr/lib/python3.10/site-packages/picker/standalone.py", line 46, in __open_main_selector_window
    read_characters_from_files(self.args.files, load_frecent_characters(), self.args.use_additional)
  File "/usr/lib/python3.10/site-packages/picker/file_loader.py", line 14, in read_characters_from_files
    for file in __resolve_all_filenames(files, use_additional):
  File "/usr/lib/python3.10/site-packages/picker/file_loader.py", line 26, in __resolve_all_filenames
    resolved_file_names += __resolve_filename(file_name, use_additional)
  File "/usr/lib/python3.10/site-packages/picker/file_loader.py", line 54, in __resolve_filename
    raise FileNotFoundError(f"Couldn't find file {file_name!r}")
FileNotFoundError: Couldn't find file '~/.local/share/rofimoji/latipun.csv'
```

but, if I run directly using command line, it works.
```sh

❯ rofimoji --files emojis nerd_font arrows ~/.local/share/rofimoji/latipun.csv
# works here
```

**Comment by igemnace** [comment]
It does actually work for me now, thanks!

**Comment by fdw** [comment]
@latipun7: Since you have a different error, I've moved it to a different issue. We'll fix that over there :)

@igemnace: Awesome, have fun 🙂
