### ISSUE TITLE
Action `type` not working on WezTerm

### ISSUE THREAD

**Issue by latipun7** [fdw/rofimoji#135]
I tried to type emoji on [WezTerm](https://wezfurlong.org/wezterm/) using rofimoji standalone.

After selecting emoji, it does not type the emoji into wezterm, but if I choose action `clipboard`, the emoji pasted correctly into wezterm.

## Info

| Env | Version |
|--------|--------------|
| rofimoji | v6.0.0 |
| WezTerm | 20221103-195702-40e08faf (nightly) |
| OS | Arch Linux x86_64 (X11) |
| xdotool | version 3.20211022.1 |

**Comment by fdw** [comment]
I can image that WezTerm doesn't play nice `xdotool` (or `ydotool`) (see also [Insertion Method in the readme](https://github.com/fdw/rofimoji#insertion-method)). Can you please try if it works without rofimoji, for example with `xdotool type ✌`?

**Comment by latipun7** [comment]
Yeah, `xdotool` works in wezterm, tried running this command and it works:
```sh
xdotool windowactivate --sync 172837 type --clearmodifiers ✌
# note, 172837 is wezterm window id get from `xdotool getactivewindow`
```

**Comment by fdw** [comment]
That's unexpected. Does it work for other programs?

**Comment by latipun7** [comment]
I tried rofimoji action `type` with kitty & brave browser. Both is working. That's why I open this issue to help investigate what is causing this behavior.

Currently, the workaround for wezterm is I use action `clipboard`.

**Comment by fdw** [comment]
In your test, did you write to the same terminal or to a different one?

**Comment by latipun7** [comment]
Sorry, it seems wezterm not printing emoji from xdotool. Actually trying to type:
```shell
xdotool windowactivate --sync 33554489 type --clearmodifiers ✌ # does not work
xdotool windowactivate --sync 33554489 type --clearmodifiers 🎨 # does not work
xdotool windowactivate --sync 33554489 type --clearmodifiers 🧑‍💻 # does not work
xdotool windowactivate --sync 33554489 type --clearmodifiers "this is ok" # works
```
Now, my issue is known issue that action `type` [not reliable on some apps](https://github.com/fdw/rofimoji#insertion-method).

**Comment by fdw** [comment]
Sorry to hear that 🙁 Maybe `clipboard` is good enough? Also, feel free to open bugs with both apps 😉

Or, if you have another idea how `rofimoji` could improve, I'm also very interested 🙂

**Comment by latipun7** [comment]
Action `menu` or `clipboard` is good enough for now. I'll close this for now. Gonna reopen or create new issue/discussion if I have idea how to improve action `type`.

**Comment by fdw** [comment]
You're welcome 😊
