### ISSUE TITLE
Type Union syntax requires Python 3.10 or higher.

### ISSUE THREAD

**Issue by mcourteaux** [fdw/rofimoji#137]
https://peps.python.org/pep-0604/ is only introduced in Python 3.10.
Rofimoji is now broken on Ubuntu 20.04, as that comes with Python 3.8.

The ironic thing is, it works if you just replace the `|` union syntax with whatever else, as python type hints are entirely ignored anyway. (I replaced them all with `,` in standalone.py and selector.py)

**Comment by fdw** [comment]
Oh, sorry! I've pushed a fix, can you please test it?

**Comment by mcourteaux** [comment]
Haven't tested it, but for sure looks good. Don't feel like going through the trouble of installing it from source instead of pip. Thanks for fixing it though :)
