### ISSUE TITLE
Shows and copies `❤` instead of `❤️`

### ISSUE THREAD

**Issue by micgro42** [fdw/rofimoji#142]
Some emojis predate color-emojis and also have a text-only representation. The most common example is the red heart. The original code-point, as copied by rofimoji, often renders in black-and-white: `❤`. However, what most people want is the original code-point followed by the "[Variation Selector-16](https://emojipedia.org/variation-selector-16/)", resulting in: `❤️`.

You can try this out by first pasting the basic red heart via rofimoji, and then directly after it pasting the Variation Selector-16 as copied from the Emojipedia link above.

I'm not exactly sure how to best implement this. But I would like to copy and paste an actually red heart when I copy the red heart.

Potentially related to #102

**Comment by fdw** [comment]
Thanks a lot, I didn't know about Variation Selectors yet! 🙂

I've added them to all emojis with a default text presentation. Should be better now 🙂

**Comment by mcourteaux** [comment]
I believe the variant selector is not actually copied into the application when entering. The emojis display correctly in rofi, but they don't get the selector once inserted.

**Comment by fdw** [comment]
That is true, and it is on purpose: I didn't want `rofimoji` to try and interpret whether you wanted the Variant Selector or not. In my experience, it's usually correctly picked up by the target app anyway.

Do you think the Variant Selector should be always included?

**Comment by mcourteaux** [comment]
> Do you think the Variant Selector should be always included?

Three options are reasonable to me:

 - CLI option to say `--vs16=always`.
 - CLI option to say `--vs16=never`.
 - CLI option to say `--vs16=list-both`.

Where I'd make `--vs16=always` be the default-implied option.

Either way, I believe that what is shown in the options menu should also be the thing that gets actually inserted in the application. If rofi shows a colorful emoji, the inserted result should be a colorful emoji. If it's an old black-and-white symbol, so should be the inserted result.

**Comment by mcourteaux** [comment]
Or maybe: `--variants=15`, `--variants=16`, and `--variants=both`.
