### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'splitlines'

### ISSUE THREAD

**Issue by hschne** [fdw/rofimoji#143]
I'm facing an issue with Rofimoji on Arch. Copying emojis with Skin tones results in the following error: 
```
Traceback (most recent call last):
  File "/home/hschne/.local/bin/rofimoji", line 8, in <module>
    sys.exit(main())
  File "/home/hschne/.local/lib/python3.10/site-packages/picker/__main__.py", line 11, in main
    ModeRofimoji().mode()
  File "/home/hschne/.local/lib/python3.10/site-packages/picker/mode.py", line 101, in mode
    self.handle_shortcuts(state)
  File "/home/hschne/.local/lib/python3.10/site-packages/picker/mode.py", line 156, in handle_shortcuts
    state.unprocessed_characters = state.current_input.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'
```
## Reproduction

1. Run Rofimoji via Rofi
  ```
  rofi -modi "emoji:rofimoji" -show emoji
  ```
2. Select some Emoji that supports skin tones, e.g. `wave`. Press Enter.
3. Select any skin tone. Press Enter.
4. The error above is raised

Funnily enough, Emojis that _don't_ support skin tones work as expected. For example, selecting an emoji such as `:heart_decoration:` work as expected. Those are copied to the clipboard on pressing enter. 

Since nobody else raised that issue I'm assuming it's something on my system, but I'd still appreciate any help. As you can imagine, Rofimoji is critical to my workflow :wink: 

## Additional Info

I installed Rofimoji using 
```
pip install --user rofimoji
```
I'm running a system with the following specs:
```
$ python --version
Python 3.10.8
$ rofi -v
Version: 1.7.5
$ rofimoji --version
rofimoji dirty (?)
```

**Comment by fdw** [comment]
Perfect, thank you and you're welcome 😊
