### ISSUE TITLE
[BUG] Unable to copy emojis with colour variations

### ISSUE THREAD

**Issue by Prayag2** [fdw/rofimoji#144]
## Summary
I'm unable to copy emojis having multiple colour variations. For example, the hand emojis with different skin colours.
Normal emojis with no variations don't have this problem.

## Expected Result
I expected it to copy the selected emoji to clipboard.

## Steps To Reproduce
1. Open rofimoji
2. Search for emojis having variations like the hand emojis.
3. Select a colour
4. Press Enter to select the emoji
5. Try to paste it or look in your clipboard history. You won't be able to paste it.

## Additional Context
Here's a video
https://user-images.githubusercontent.com/39525869/209508499-8a75f563-17a6-4afd-981a-615a96ce2f66.mp4

**Comment by fdw** [comment]
The video doesn't work 🙁

Does the emoji end up in your clipboard history?
Which version of `rofimoji` are you using? Are you using `rofimoji` standalone or as a `rofi` mode?

**Comment by Prayag2** [comment]
> The video doesn't work :slightly_frowning_face:

You can try downloading it. It works fine in MPV or VLC (i used ffmpeg to record it so maybe that's why it doesn't work on browsers).

I'm using this command to run it
`rofi -modi "emoji:/usr/bin/rofimoji" -show emoji -display-emoji "ﲃ"`

**Comment by fdw** [comment]
Then I guess you're also a victim of #143. Current `main` should contain the fix, and I'll try to release a new version in the next days.

I'll close this, but if you see a different error, feel free to re-open 🙂

**Comment by Prayag2** [comment]
Okay, thanks!
