### ISSUE TITLE
How to start rofimoji as standalone tool?

### ISSUE THREAD

**Issue by MaxGyver83** [fdw/rofimoji#147]
In the past, I started rofimoji like this:

```sh
PYTHONPATH=~/repos/rofimoji/src python3 -m picker
```

After pulling the latest `main`, this does not work anymore. So I checked the README:
It tells me to run `rofimoji.py`. But this file doesn't exist (anymore). I guess, `src/picker/standalone.py` is the replacement.

But none of these works:

```sh
python3 src/picker/standalone.py
```

```sh
cd src/picker && python3 standalone.py
```

```sh
PYTHONPATH=~/repos/rofimoji/src python3 -m picker
```

```sh
PYTHONPATH=~/repos/rofimoji/src python3 -m picker.standalone
```

**Comment by fdw** [comment]
First, sorry for the outdated documentation! That line really slipped my mind when I updated everything else...

Have you installed `rofimoji` from pip or the package? Then you can just call `rofimoji` and it should work.

If you only cloned the repo, you probably need to use `poetry` to first install the dependencies (`poetry install`) and then run it `poetry run python -m picker` (both from the main folder).

Does that help? If not, do you get any error messages?

**Comment by MaxGyver83** [comment]
I have tried both pip and poetry. Both did work. Thank you!

Do you really need all these dependencies? I guess installing poetry + dependencies + rofimoji's poetry dependencies take ≥ 80 MB disk space.

Now I'm using the poetry approach because I made this little local change to the source code to get a larger font size:

```diff
diff --git a/src/picker/selector/selector.py b/src/picker/selector/selector.py
index 4b84fe1..097dfc7 100644
--- a/src/picker/selector/selector.py
+++ b/src/picker/selector/selector.py
@@ -66,6 +66,8 @@ class Rofi(Selector):
     ) -> Tuple[Union[Action, DEFAULT, CANCEL], Union[List[str], Shortcut]]:
         parameters = [
             "rofi",
+            "-font",
+            "mono 24",
             "-dmenu",
             "-markup-rows",
             "-i",
```

Can this somehow be achieved with a command line argument? (I couldn't find something that looks like it could do this.)

**Comment by MaxGyver83** [comment]
I use Arch, btw :-) and just noticed that I can install `rofimoji` also via pacman. Pacman says this package needs only 3 MB. This sounds good!

**Comment by fdw** [comment]
`rofimoji` is kinda small (the unicode files take most of the space), and it doesn't have many dependencies. So I guess the 80MB come from Poetry and its friends.

Regarding arguments for `rofi`, you should try `--selector-args` 😉

**Comment by MaxGyver83** [comment]
Great! Thank you.
Then I need only the pip or the pacman package.

For future readers: Make sure you use it like this if the first selector arg starts with a dash:

```sh
rofimoji --selector-args='-font "mono 24" -theme-str "window {width: 80%;}"'
```

(It doesn't work with a space instead of the equal sign because then `-font` is interpreted as another flag for rofimofi itself.)

**Comment by fdw** [comment]
> (It doesn't work with a space instead of the equal sign because then `-font` is interpreted as another flag for rofimofi itself.)

Yep, that is a [known bug in argparse](https://bugs.python.org/issue9334) and described in the [readme](https://github.com/fdw/rofimoji#options)

**Comment by MaxGyver83** [comment]
Oh, I should have read the README more carefully!
