### ISSUE TITLE
Launching rofi through rofimoji doesn't respect scaling

### ISSUE THREAD

**Issue by skiletro** [fdw/rofimoji#157]
As the title says. Launching rofi directly uses the right scaling, but launching it through rofimoji causes it to use the default 1x scaling.

## Images
Through rofimoji
![image](https://github.com/fdw/rofimoji/assets/19377854/f84205c6-8839-4a41-82dd-15f9ca028d5e)
Through rofi
![image](https://github.com/fdw/rofimoji/assets/19377854/6410e3b5-d423-401a-a7bd-4a3d5fffc176)

## Additional Information
NixOS 23.11
Rofimoji 6.1.0
Rofi 1.7.5+wayland2

**Comment by fdw** [comment]
Thanks for that report 🙂

Where/how is the correct scaling defined?

**Comment by skiletro** [comment]
I'm not too sure, but after further inspection I believe it's because running `rofi` directly is launching it in wayland mode (per the version I'm using), but running it through rofimoji is running it through Xorg, hence it not respecting the scaling.

**Comment by fdw** [comment]
Hm, `rofimoji` should call the same `rofi` binary as you do. Do you have some unusual setup in regard to `rofi`?

**Comment by skiletro** [comment]
Only things that come to mind is some weirdness with NixOS, or the fork of rofi I'm using to add Wayland support?

**Comment by fdw** [comment]
I'm using https://github.com/lbonn/rofi , but on X. If you're using the same fork, that shouldn't be the problem.

You can tell `rofimoji` to use a certain selector with `--selector rofi`. If you try that, does it look better?

**Comment by skiletro** [comment]
I'm using that fork as well, but on Wayland. I get the same result (small size) when running `rofi -x11` to force it to run in X11 mode, so it seems like it's being forced to run in X11 for whatever reason.

**Comment by fdw** [comment]
If you call `rofimoji --selector rofi`, what happens? And how do you start `rofimoji`?

**Comment by skiletro** [comment]
Running the first command does the same thing as it's been doing, and I'm launching it currently just from a terminal, but running it as a bind through Hyprland yields the same result.

**Comment by fdw** [comment]
The only thing I can currently imagine is that, for some reason, you have the old X.org rofi also installed and rofimoji chooses the wrong one. Would that be possible with Nix?

**Comment by skiletro** [comment]
Ive never installed the regular version of rofi on my system so that's not possible.

**Comment by fdw** [comment]
Hm. `rofimoji` just launches the `rofi` binary, whatever that may be. Environment variables should also be passed through. I cannot see what would lead `rofi` to think it's in X now...

**Comment by skiletro** [comment]
After further investigation, I believe the issue relies on the way the [NixOS Package](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/applications/misc/rofimoji/default.nix#L52) has been packaged, using it's own version of rofi rather than using rofi-wayland? I'm still a novice when it comes to NixOS so I'm unsure how it would be fixed, but it's not the fault of the code.

Sorry to have wasted your time.

**Comment by fdw** [comment]
Ha, thank you! I was really flabbergasted by that, so thanks for clearing it up 🙂
Maybe you can open an issue there?

Also, no worries about time wasting, I'm happy to help and for people to use `rofimoji` 😊

**Comment by CardboardTurkey** [comment]
> After further investigation, I believe the issue relies on the way the [NixOS Package](https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/applications/misc/rofimoji/default.nix#L52) has been packaged, using it's own version of rofi rather than using rofi-wayland? I'm still a novice when it comes to NixOS so I'm unsure how it would be fixed, but it's not the fault of the code.
> 
> Sorry to have wasted your time.

Ah thank you this helped me locate the issue!

For anyone seeing this you can fix it with

```nix
environment.systemPackages = with pkgs; [
  (rofimoji.override { rofi = rofi-wayland; })
]
```
