### ISSUE TITLE
Problem typing with rofi

### ISSUE THREAD

**Issue by micah** [fdw/rofimoji#159]
I am using swaywm on Wayland, with the foot terminal. When I try to use rofi to call rofimoji, I am able to get the emoji picker, but nothing is emitted to the terminal. If I call rofimoji directly, it does appear.

When I call it with rofi, I'm doing the following:

`/usr/bin/rofi -theme solarized -modi emoji:~/bin/rofimoji -show emoji`

I then find my favorite emoji Press enter on the emoji. Nothing is emitted into the terminal, and the command returns a zero exit code.

If I run `rofimoji --action type` I then can pick my emoji, hit enter, and the emoji is emitted on the terminal.

I've tried various incantations of --typer and --action, but I can't seem to get it to work.

Curiously, and unhelpfully, this used to work fine. I'm using wtype 0.4-3, if that helps.

**Comment by fdw** [comment]
This is interesting, because it's not supposed to work: [Because rofi is the main process, rofimoji cannot directly type to any window. Only copying the character works, so set the --action accordingly.](https://github.com/fdw/rofimoji#caveats-when-running-rofimoji-as-a-rofi-mode)

So, I hope calling `rofimoji` directly is acceptable to you, because it's a lot more powerful.

**Comment by micah** [comment]
Indeed, calling it directly is acceptable to me, for some reason I didn't understand that I could do that.

Additionally, it appears I misread the statement, "Because rofi is the main process, rofimoji cannot directly type to any window. Only copying the character works, so set the --action accordingly." thinking that I could set the action to `type` and it would work. Obviously, that is an incorrect understanding of that sentence.

I'm not sure how it worked before, but no matter, as calling `rofimoji` directly works, as you said. 

Thank you, and sorry for wasting your time!

**Comment by fdw** [comment]
No worries, I like to help 🙂
