### ISSUE TITLE
Tofi launcher support?

### ISSUE THREAD

**Issue by ZerdoX-x** [fdw/rofimoji#160]
I see that rofi, wofi and fuzzel are supported.
Is it possible to use emoji picker with [tofi](https://github.com/philj56/tofi)?

Usually I just patch dmenu scripts manually so they would support tofi, but this is not the case as you can't just dump all emojis into launcher. If needed, I can provide these scripts, currently I have integration with [pass](https://www.passwordstore.org/) and [cliphist](https://github.com/sentriz/cliphist).

**Comment by fdw** [comment]
Seems straightforward enough, so yes. Do you want to have a go at it? You'd need to add a new class to [`selector.py`](https://github.com/fdw/rofimoji/blob/main/src/picker/selector/selector.py), similar to the other ones. As far as I can see, tofi doesn't support any fancy configuration, so it's probably the same implementation as for dmenu.

I can also add it, when I have time.

**Comment by ZerdoX-x** [comment]
> Seems straightforward enough, so yes.

Nice, glad to hear.

> Do you want to have a go at it? You'd need to add a new class to [selector.py](https://github.com/fdw/rofimoji/blob/main/src/picker/selector/selector.py), similar to the other ones.

I could try later but better to not rely on me in context of this feature, I will be busy next few weeks.

**Comment by fdw** [comment]
Hey, I had some time, so I added tofi. Can you please try it?

**Comment by ZerdoX-x** [comment]
Sure. I'll try in a few days, maybe even today. Thank you!

**Comment by ZerdoX-x** [comment]
Launching `rofimoji` from terminal, getting this:
![image](https://github.com/fdw/rofimoji/assets/49815452/cab44aaa-21bf-4a11-9a24-f087c0a5d28c)
I can search, all fine. But when I am choosing emoji, it gets crashed:
```
Traceback (most recent call last):
  File "/home/zerdox/.local/bin/rofimoji", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/zerdox/.local/pipx/venvs/rofimoji/lib/python3.11/site-packages/picker/__main__.py", line 9, in main
    StandaloneRofimoji().standalone()
  File "/home/zerdox/.local/pipx/venvs/rofimoji/lib/python3.11/site-packages/picker/standalone.py", line 41, in standalone
    execute_action(characters, self.args.actions, self.active_window, self.args.typer, self.args.clipboarder)
  File "/home/zerdox/.local/pipx/venvs/rofimoji/lib/python3.11/site-packages/picker/action.py", line 20, in execute_action
    typer.type_characters(characters, active_window)
  File "/home/zerdox/.local/pipx/venvs/rofimoji/lib/python3.11/site-packages/picker/typer/noop.py", line 17, in type_characters
    raise NoTyperFoundException()
picker.typer.noop.NoTyperFoundException: Could not find a valid way to type characters. Please check the required dependencies.
```

Also when I run command and Tofi appears, my cursor fully disappears, not sure, is this somehow handled by rofimoji?

Probably in order to use rofimoji properly I need to add a `.desktop` file with proper configuration, but currently I am just running rofimoji with stock config.

**Comment by fdw** [comment]
You don't have any app installed to type the selected emoji. You probably want `xdotool` or `ydotool`, depending on your setup. Or you don't want to type at all, but then you should set `--action`.

Regarding the cursor, that's not something `rofimoji` does on purpose. I've also not found any parameter of `tofi`'s that would do that.

**Comment by ZerdoX-x** [comment]
> Regarding the cursor, that's not something rofimoji does on purpose. I've also not found any parameter of tofi's that would do that.

Yeah, I tried to run `tofi-drun` from terminal and it eats my cursor.

> You don't have any app installed to type the selected emoji. You probably want xdotool or ydotool, depending on your setup.

Oh, okay, got it. Would be really nice if `rofimoji` could catch it and print nicely to inform user. This is probably mentioned in the docs as optional dependencies, I just missed it.

> Or you don't want to type at all, but then you should set --action.

Yes, actually I think I would like to just copy emoji by default, so I'll just configure rofimoji to my requirements and let you know if I'll encounter any issues with rofimoji on tofi. Once again, thank you for implementing this :heart:

**Comment by fdw** [comment]
> Would be really nice if rofimoji could catch it and print nicely to inform user.

It kinda does, it's just hidden by the stacktrace: `picker.typer.noop.NoTyperFoundException: Could not find a valid way to type characters. Please check the required dependencies.` 😉

> I think I would like to just copy emoji by default

Either call it with `--action copy` or set `action = copy` in `.config/rofimoji.rc`

> Gave a ⭐ to rofimoji :)

❤️ Thank you! 🙏

**Comment by ZerdoX-x** [comment]
Hi. I have tried to use rofimoji. Currently zero config and have `ydotool` and `wtype` installed.

Error I get when select :+1: emoji:
```
Traceback (most recent call last):
  File "/home/zerdox/.local/bin/rofimoji", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/zerdox/.local/pipx/venvs/rofimoji/lib/python3.11/site-packages/picker/__main__.py", line 9, in main
    StandaloneRofimoji().standalone()
  File "/home/zerdox/.local/pipx/venvs/rofimoji/lib/python3.11/site-packages/picker/standalone.py", line 35, in standalone
    characters = self.__process_chosen_characters(value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerdox/.local/pipx/venvs/rofimoji/lib/python3.11/site-packages/picker/standalone.py", line 66, in __process_chosen_characters
    characters_with_skin_tones.append(self.__add_skin_tone_to_character(character))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerdox/.local/pipx/venvs/rofimoji/lib/python3.11/site-packages/picker/standalone.py", line 75, in __add_skin_tone_to_character
    characters_with_skin_tone.append(self.__select_skin_tone(element))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerdox/.local/pipx/venvs/rofimoji/lib/python3.11/site-packages/picker/standalone.py", line 94, in __select_skin_tone
    return_code, skin_tone = self.selector.show_skin_tone_selection(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerdox/.local/pipx/venvs/rofimoji/lib/python3.11/site-packages/picker/selector/tofi.py", line 34, in show_skin_tone_selection
    tofi = run(
           ^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dmenu'
```

Maybe I can workaround this by setting preferred skin tone in the settings, not sure.

---

And I get this error when trying to select :grapes: emoji:
```
Failed to deencode input argv
```

This one is definitely from here: [atx/wtype/main.c#L294-L296](https://github.com/atx/wtype/blob/d71be3a7b3f93b534a2823fd68cabd7ac2a02359/main.c#L294-L296). But I am not sure what it causes.

---

Currently for reproduction I call `rofimoji` from terminal and switch to other terminal or window in order to see if something get's typed and if error occures.

And also skin tone selector as expected also doesn't work when I force copy action. In general, currently it's usable with tofi if you set `copy` action and skin tone in config. Please let me know what do you think about these two issues above, thank you :)

**Comment by fdw** [comment]
So, this is actually several problems:

First, I made a mistake and even with `tofi` as selector, `dmenu` is called in one instance. Because you haven't installed that, `rofimoji` dies. (See the last line of the error message.)

About `wtype`, I have currently no idea. Can you copy a character to the clipboard, or does that fail, too?

Finally, `--hidden-descriptions` uses some `rofi` magic to still have searchable but invisible descriptions. It seems that `tofi` doesn't like that.

**Comment by ZerdoX-x** [comment]
> First, I made a mistake and even with `tofi` as selector, `dmenu` is called in one instance. Because you haven't installed that, `rofimoji` dies. (See the last line of the error message.)

Yep, I got it. I guess you fixed that already, I'll try to test it in a few days.

> About wtype, I have currently no idea. Can you copy a character to the clipboard, or does that fail, too?

I can use `copy` and `clipboard`, but not a default action which is called "type" afair.

> Finally, --hidden-descriptions uses some rofi magic to still have searchable but invisible descriptions. It seems that tofi doesn't like that.

Yep, I thought of this. How can I formalize this in order to request new feature in tofi to support this? What kind of magic is this? If this isn't too magical, I can try to request it as implemented in rofi.

---

I'll update rofimoji, remove preferred skin tone from setting and see how it goes, thank you :)

So currently the only issue is error from wtype.. I also have no ideas about this. Does rofimoji use ydotool or only wtype is supported? If needed to, I can test from another git branch you'll set up to provide any info you want, in case if we can implement any logging to get extra info from issue which can be reproduced by me.

**Comment by ZerdoX-x** [comment]
Skin tone selection fixed, thank you 👍🏻👍🏾

**Comment by fdw** [comment]
I've moved the `wtype` bug to its own issue: #164.

About the `--hidden-descriptions`, see here: https://github.com/davatorium/rofi/pull/1052 and https://github.com/davatorium/rofi/blob/next/doc/rofi-script.5.markdown#parsing-row-options

**Comment by ZerdoX-x** [comment]
So we can close this now I think. Skin tone selection works, so selector implemented fine. The only remaining issues are
 - lack of feature from rofi, but it's not related to rofimoji
 - wtype itself not being able to type :grapes:
