### ISSUE TITLE
[FEATURE REQUEST] Lenny faces ( ͡° ͜ʖ ͡°)

### ISSUE THREAD

**Issue by grappas** [fdw/rofimoji#162]
Could you add lenny faces, or at least possibility to plug your own emotes?

https://raw.githubusercontent.com/cspeterson/splatmoji/master/data/emoticons/emoticons.tsv

**Comment by fdw** [comment]
If you have a good source for them (with an appropriate license), then it should be easy to add. You can have a look at the [existing extractors](https://github.com/fdw/rofimoji/tree/main/src/extractors) for examples.

And it's already possible to add your own characters: https://github.com/fdw/rofimoji#custom-character-files-and-descriptions

**Comment by fdw** [comment]
I'll close this issue for now. Please re-open if you have a good source for them. Or open a PR 😉

**Comment by grappas** [comment]
> I'll close this issue for now. Please re-open if you have a good source for them. Or open a PR 😉

@fdw isn't good what I provided?

**Comment by fdw** [comment]
There is already a way to add your own characters of any kind, and I already linked [the relevant readme section](https://github.com/fdw/rofimoji#custom-character-files-and-descriptions). If you have questions about it, please ask them 🙂

Also, I'd look at a PR to add an extractor, if you want to write one. Please make sure that the license for the data is permissive enough. In this case, it seems the original source is https://github.com/w33ble/emoticon-data , which has a good license and should be easy to use, given that it's json.

**Comment by fdw** [comment]
Then please describe your issue! In your original post, you just asked
> Could you add lenny faces, or at least possibility to plug your own emotes?

and I answered both questions. How can I know that you tried it and had problems?

In the original file you linked, the faces are separated from their description with tabs. However, `rofimoji` expects spaces. If you change that, it works fine for me.
However, as some faces already contain spaces, that will not work. Unfortunately, supporting that is probably a very large and breaking change.

**Comment by grappas** [comment]
> and I answered both questions. How can I know that you tried it and had problems?

https://github.com/fdw/rofimoji/assets/1036957/c82bf032-c903-4c3e-ba69-34d1d5ea1935

[lennies.additional.csv](https://github.com/fdw/rofimoji/files/13589102/lennies.additional.csv)

In theory quotations of objects and separating them with commas or semicolons would suffice.

>  supporting that is probably a very large and breaking change.

Large? Agreed. But breaking? nah... Just make it backward compatible with old files.

**Comment by grappas** [comment]
At least make space escapeable... with \

**Comment by fdw** [comment]
As I said, it's not just about parsing the file, but also about the communication with `rofi`. Even if I add escaping for spaces, that would be visible in `rofi`.

I'll think about it, but don't get your hopes up.

**Comment by fdw** [comment]
I've finally tried to use a real csv format for the data files, which would be the first step to enable characters with spaces. However, the performance is much worse than with the simpler format currently used - loading a file now takes five times as long as before. If you try to open many `--files`, it's noticeable slower and worse. For this reason, I don't think I'll continue on this path.

Maybe I'll change my opinion at some point in the future, if there's a compelling reason. And I'm still willing to look at PRs.
