### ISSUE TITLE
[Feature Req]: Gif support

### ISSUE THREAD

**Issue by niksingh710** [fdw/rofimoji#165]
Is it possible to add GIF support?
I am unable to figure out a way to get the preview of the GIF before selecting it in rofi ...... 
but it is possible to show the image preview in rofi menu
as mentioned by a redditor 
```bash
ls ~/Pictures/ | while read A ; do  echo -en "$A\x00icon\x1f~/Pictures/$A\n" ; done | rofi -dmenu
```

i am curious if extracting the first frame from the gif and showing it as preview.?

**Comment by fdw** [comment]
I'm not sure what you're asking here. If you want general support for gif previews in `rofi`, you should ask [over there](https://github.com/davatorium/rofi).

This repo is for `rofimoji` which helps you selects characters like emojis (or a series of characters). But I don't intend to extend it to images or gifs, sorry.
