### ISSUE TITLE
[Font Problem] Most emoji are not shown

### ISSUE THREAD

**Issue by rew1nter** [fdw/rofimoji#167]
* What does rofimoji show instead of the emojis? Can you please share a screenshot (`Alt+Shift+s** in rofimoji)
screenshot shortcut doesn't work rofi is up
* What do other apps like Firefox/Chrome/your text editor show instead of emojis?
 They show correctly when copy pasted from rofimoji or nerdfont cheatsheet
In terminal, It shows correct emoji when I copy paste from nerdfont. but copypasting from rofimoji to terminal doesn't show the emoji
* Which emoji fonts do you have installed?
 Jetbrains mono nerd font and a few more
* Are the emoji fonts set in your font config?
No
* Which versions of rofimoji and pango are installed?
rofimoji 6.2.0
pango-list (pango) 1.51.0

what's pango btw?

**Comment by fdw** [comment]
Without seeing what you see instead, I cannot really help, sorry. Have you had a look through the other bugs with font problems?
Are you using `rofi` or something else? Since you mentioned nerdfonts, do they show up?

**Comment by rew1nter** [comment]
![image](https://github.com/fdw/rofimoji/assets/64508791/a293f35f-78bf-4a7a-b419-e67fd66729ad)
There you go 
Yes I'm using rofi

**Comment by rew1nter** [comment]
![image](https://github.com/fdw/rofimoji/assets/64508791/063b98b0-4fa5-45c9-9b1c-0b9bf257362c)
nerd fonts show up in terminal

**Comment by fdw** [comment]
Thanks, that helps a lot. It seems to me that you don't have a real emoji font installed. Jetbrains mono nerd font includes nerd font symbols, but I have no idea if it includes actual emoji characters.

Maybe you could try Noto Emoji.

**Comment by rew1nter** [comment]
Installing Noto Emoji fixed the problem :D 
Is there any other emoji font I can install instead of Noto Emoji that'll work with rofimoji?
Thank you

**Comment by fdw** [comment]
Sure, all you need is a font that contains these symbols. Most "normal" fonts don't, but there are several other emoji fonts. Just find one that you like 🙂
