### ISSUE TITLE
Add kaomoji

### ISSUE THREAD

**Issue by fdw** [fdw/rofimoji#182]
From #181: If we replace the spaces in kaomoji with non-breaking spaces, everything should work - and it would even be very correct, as you don't want your kaomoji to be broken up.

**Comment by fdw** [comment]
Could you please try the new branch `kaomoji` and see if that works for you?

I've used the kaomoji list at https://github.com/w33ble/emoticon-data . If you have a better source, please share 🙂

**Comment by niksingh710** [comment]
https://github.com/w33ble/emoticon-data This resource seems to have much more than I expected.

I have just tested the `kaomoji` branch, and it seems to be working fine as expected.

I will be waiting for this to get merged in master branch so that I can have it installed via `AUR`.

**Comment by niksingh710** [comment]
For some reason, `rofimoji-git` aur package is failing to install.

And the default rofimoji package on arch repos is giving this error
```bash
󰘧 rofimoji -h
Traceback (most recent call last):
  File "/usr/bin/rofimoji", line 5, in <module>
    from picker.__main__ import main
ModuleNotFoundError: No module named 'picker'
```

In the meantime, I will be using it from manual compilation.
If you can do a normal release for the package as it's been 6 months since the last release.
I can ask the Arch official repos to check if the failure is causing because of package building.

**Comment by fdw** [comment]
I'm not involved in the AUR package (or any other), but I could install it without problems. Maybe try again?

Apart from that, I do plan to release a new version soon. However, I want to wait for a bit so that problems with the latest changes can pop up.

**Comment by niksingh710** [comment]
> I'm not involved in the AUR package (or any other), but I could install it without problems. Maybe try again?


The issue was from my side because of partial update now fixed and all working fine.
