### ISSUE TITLE
Characters not showing up in searches after they've been selected once before

### ISSUE THREAD

**Issue by toxision** [fdw/rofimoji#184]
Hi!

As briefly mentioned this started to happen with 6.3.0.
Previously have used the latest version 6.2.0 without issues and updated via pip install.

As shown, the emojis from recent selection loosing their context texts and thus, cannot be searched anymore. Interestingly, removing the frecency file, temporarily fixes the problem. At least until the same emoji is being searched again. Therefore, using the --no-frecency flag, seems to resolve it.

![image](https://github.com/fdw/rofimoji/assets/71572691/986be2a8-f000-4523-a8e8-df8afc341609)

I am spawning it via: /home/toxision/bin/rofimoji --selector-args="-theme /usr/share/rofi/themes/android_notification.rasi"
But also plain 'rofimoji' results in same problem. So theme file seems to have nothing to do with it.
Installed emoji fonts and versions:
- Package: fonts-emojione
Version: 2.2.6+16.10.20160804-0ubuntu2
- Package: fonts-noto-color-emoji
Version: 2.042-0ubuntu0.22.04.1

No other configs or tweaks applied.

**Comment by fdw** [comment]
I think I found the problem. Could you please test the branch `fix/frecency-merging` if that solves it?

**Comment by toxision** [comment]
Thanks for the quick help. Although I am afraid I can't test it....limited knowledge about python 😿

**Comment by fdw** [comment]
No worries 🙂
Would it be possible for you to check out the branch and install `poetry-python`? If so, all you'd need to do is call `poetry install` and `poetry run python -m picker` in `rofimoji`'s directory.

**Comment by fdw** [comment]
Thanks you! But that looks like a strange error, maybe you have an old Poetry version...

Instead, I built you a wheel file, maybe it's easier for you to install that.
[rofimoji-6.3.0.tar.gz](https://github.com/fdw/rofimoji/files/15209596/rofimoji-6.3.0.tar.gz)

**Comment by polyzen** [comment]
> I think I found the problem. Could you please test the branch `fix/frecency-merging` if that solves it?

Cherry-picked the fix and it does the job, thank you 😁

**Comment by fdw** [comment]
Awesome, I've merged it to `main`. Will do a new release soon.
