### ISSUE TITLE
Where to put --action in rofi mode? Cannot get copy as default action

### ISSUE THREAD

**Issue by boresk** [fdw/rofimoji#187]
I'm trying to change the default action in rofi mode. Is it something possible? I've installed rofimoji from nix and I'm using a debian distro. I am able to copy the emoji with alt+shift+1.

`rofi -modi 'emoji:rofimoji ' --action copy -show emoji -theme ~/.config/rofi/launchers/type-2/style-1.rasi`

**Comment by fdw** [comment]
You need to pass it as a parameter to `rofimoji`, not to `rofi`. So: `rofi -modi 'emoji:rofimoji --action copy' -show emoji -theme ~/.config/rofi/launchers/type-2/style-1.rasi`. Or you put it in the config file.

**Comment by boresk** [comment]
I get the following error:

`rofimoji: error: argument --action/-a: invalid Action value: 'ℹ information <small>(i, information)</small>'

Seems like the emoji is passed to action

**Comment by fdw** [comment]
Have you used `copy` or `type` for the action?

**Comment by boresk** [comment]
copy (exactly like you've typed)

**Comment by fdw** [comment]
Can you try `rofi -modi 'emoji:rofimoji --action=copy' -show emoji` please?

**Comment by boresk** [comment]
That works, thanks a lot!
