### ISSUE TITLE
[feature request] pass arguments to rofi

### ISSUE THREAD

**Issue by nimobeeren** [fdw/rofimoji#19]
I would like to pass some parameters to rofi that I don't use in my main rofi config. For example, I like to use 3 columns with rofimoji, but when I use rofi in any other mode I use 1.

I suggest passing on any arguments that start with a single `-` to the `rofi` call. Then I could run `rofimoji -columns 3` to get the desired effect.

**Comment by fdw** [comment]
You can try this now 😉

I chose not to differentiate between `-` and `--` arguments, as that would be nightmare to support and understand (also for the user). Also I'd like rofimoji to adhere to the convention where long arguments are prefixed with two dashes.
