### ISSUE TITLE
I cannot make it to copy the emoji

### ISSUE THREAD

**Issue by moshpirit** [fdw/rofimoji#190]
When executing this command `rofi -modi "emoji:rofimoji" -show emoji --dpi 200`, rofi shows up, but nothing else happen but this error:

```shell
Traceback (most recent call last):
  File "/usr/bin/rofimoji", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/picker/__main__.py", line 11, in main
    ModeRofimoji().mode()
  File "/usr/lib/python3.12/site-packages/picker/mode.py", line 107, in mode
    self.execute_actions(state)
  File "/usr/lib/python3.12/site-packages/picker/mode.py", line 228, in execute_actions
    save_recent_characters(state.processed_characters, self.args.max_recent)
TypeError: save_recent_characters() missing 1 required positional argument: 'files'
```

I am using AUR version. If I use `rofimoji`, it works fine, but it uses the default style. And if I use `rofimoji --selector-args="-config ~/.config/rofi/launchers/type-2/style-emoji.rasi --action=copy --clipboarder xclip"` it doesn't get copied (I tried with clipboard as action, without the clipboarder nor the config arguments too, even with nothing but loading the config).

**Comment by moshpirit** [comment]
> With "AUR version", do you mean `rofimoji-git`? Or plain `rofimoji` (which should come from `community`, I think, not the AUR)?

Sorry, you're absolutely right, I'm using the community version.

> rofimoji --selector-args="-config ~/.config/rofi/launchers/type-2/style-emoji.rasi" --action=copy --clipboarder xclip

It definitely does! I thought that everything else were arguments, but it makes total sense this way: the arguments are for rofi, the action for rofimoji. BTW, is it possible to concatenate actions? (copying and typing, for example?)

**Comment by fdw** [comment]
> Sorry, you're absolutely right, I'm using the community version.

I just checked, and the fix for your original problem is still unreleased. I'll try to release in the next days.

> BTW, is it possible to concatenate actions? (copying and typing, for example?)

Yes, that should work 🙂

**Comment by moshpirit** [comment]
> I just checked, and the fix for your original problem is still unreleased. I'll try to release in the next days.

great, thanks!

>Yes, that should work 🙂

May I ask how? `rofimoji --selector-args="-config ~/.config/rofi/launchers/type-2/style-emoji.rasi" --action=type --action=copy` only copies the emoji, and vice versa, it only takes into account the last action.

**Comment by fdw** [comment]
You should be able to just concatenate them like `--action type copy`.

**Comment by moshpirit** [comment]
> You should be able to just concatenate them like `--action type copy`.

It works! Thanks! I've just seen it in the Readme! Sorry for adding extra comments here

**Comment by fdw** [comment]
You're welcome! Have fun!
