### ISSUE TITLE
Laugh with tears emoji is not shown

### ISSUE THREAD

**Issue by rew1nter** [fdw/rofimoji#194]
Why is it not available?
![image](https://github.com/fdw/rofimoji/assets/64508791/a97ad43a-ba0f-4bbd-9fac-a614c25b22fb)

**Comment by rew1nter** [comment]
The command:
```bash
rofi -modi "emoji:/usr/bin/rofimoji --action copy --clipboarder xclip" -show emoji -theme /home/vague/.config/rofi/launchers/type-1/style-7.rasi
```
Version: rofimoji 6.3.2

Yeah this emoji used to show up before. I don't know what happened and how it ended up disappearing. Also it always remains on `0:` 
Is there a way to maybe reset rofimoji?

**Comment by fdw** [comment]
The recent characters are saved in `~./local/share/rofimoji/recent`. If you remove that (or just delete the appropriate line), it should work again.

**Comment by rew1nter** [comment]
So I removed this file, searched the laugh with tears emoji from rofimoji and it was copied to my clipboard as expected. 
But now it's back to the same thing again 
![image](https://github.com/user-attachments/assets/a138b631-8ee5-4fe8-937f-6a67dd71f623)

**Comment by fdw** [comment]
Does that happen for any other emoji? Do you have anything in `.local/share/rofimoji/data`?

**Comment by fdw** [comment]
Ha, I think I found the bug. Can you maybe try the `main` branch and report if that works better now?

**Comment by rew1nter** [comment]
I just installed it from the AUR. The bug seems to be gone. Good job!
