### ISSUE TITLE
No icons show up when using --use-icons

### ISSUE THREAD

**Issue by alba4k** [fdw/rofimoji#196]
![immagine](https://github.com/user-attachments/assets/a3c02d50-8f74-4261-8465-69ea376653e6)

![immagine](https://github.com/user-attachments/assets/033f62f3-a8cd-43a9-8698-5dcd951d99d8)

using lbonn's fork for rofi on wayland

**Comment by fdw** [comment]
Does your rofi theme support icons?

**Comment by alba4k** [comment]
Icons appear just fine in drun mode and when using cliphist (where image previews appear as icons

**Comment by Procrat** [comment]
I'm experiencing the same. Here's a minimal example with `rofi` and no `rofi` config nor `rofimoji` config: `rofimoji --use-icons --selector-args='-show-icons'`. Not using the fork mentioned by OP and running in Xorg.

**Comment by fdw** [comment]
Can you please share your rofi theme? It works for me with
```
configuration {
  show-icons: true;
}
```

You can also try to use the provided `grid-icons-only.rasi` with `--use-icons --hidden-descriptions`.

**Comment by fdw** [comment]
Also, can you please add some more information: What are the versions of `rofimoji` and `rofi`? Are you using the rofi mode or `rofimoji` standalone?

**Comment by alba4k** [comment]
whatever is in the arch repos. Can't check much sadly as I broke my laptop a couple of days ago.

was using rofimoji standalone

ended up settling with the grid theme with icons removed completely and just the emoji so it's fine

**Comment by LiamSnow** [comment]
For me running `rofimoji --use-icons --hidden-descriptions` works, but `rofimoji --use-icons` does not. I tried using a variety of themes, including the `grid-icons-only.rasi` with no luck.

I am running the current versions in Pacman:
 - `rofi-wayland 1.7.5+wayland3-2`
 - `rofimoji 6.3.2-1`

**Comment by fdw** [comment]
Thank you, that helped a lot 🙂 I could reproduce it and hopefully fixed it on `main`. Can you please try it out?

**Comment by Procrat** [comment]
That works for me, @fdw! Thank you for investing your time and the fast turnaround at fixing this! 🙏

**Comment by fdw** [comment]
You're welcome! I've just pushed out a release 🙂
