### ISSUE TITLE
A good kaomoji website

### ISSUE THREAD

**Issue by hongjiang11** [fdw/rofimoji#197]
cute kaomoji supports three languages
English https://www.cute-kaomoji.com/
Japanese https://www.cute-kaomoji.com/ja
Spanish https://www.cute-kaomoji.com/es
![1](https://github.com/user-attachments/assets/1a5e0dd3-884a-42e0-88fa-8954ee53e716)

**Comment by fdw** [comment]
Hey, thank you for that! Unfortunately, I can't find a license there - have you seen one?
