### ISSUE TITLE
Nerd Font extractor: Omit "removed" (deprecated) icons

### ISSUE THREAD

**Issue by reeseovine** [fdw/rofimoji#198]
According to https://www.nerdfonts.com/cheat-sheet:

> With Release v3.0.0 the Material Design Icons were updated and moved to new codepoints (reasons for that are in the release notes).
They are still shown here for reference, but are missing in the actual fonts.
To find for example the replacement for nf-mdi-altimeter enter just altimeter in the search box.

Since these `nf-mdi-*` icons are still included, there are a whole bunch of results with wrong/missing characters.

![image](https://github.com/user-attachments/assets/0f814bbb-f493-4010-a52b-5d8938e0004e)

One possible solution I can think of would be to modify the bs4 query to look for and omit `.column` elements with a `.corner-red` inside.

![image](https://github.com/user-attachments/assets/7e4e95b6-9a5a-48d4-970c-ea85183bf521)

**Comment by fdw** [comment]
Huh, thanks, I never noticed. Are you interested in writing a PR for that?

**Comment by reeseovine** [comment]
Sure! I did attempt it once already but:

1. how do I develop Poetry applications? I'm reading the docs and it looks like a whole suite of tools I'm not familiar with
2. I'm not sure what the best / most efficient way is to go about filtering elements from a selection, but I'll figure that out once I get past (1)

Basically, I have memory loss and I don't at all remember what I've contributed to this repo before (which github says I have), so a little direction would be very much appreciated <3

**Comment by fdw** [comment]
Sorry I didn't get back to you sooner, life got in the way...

While updating to Unicode 16, I noticed that the old NerdFont extractor didn't work at all anymore, and so I fixed it 😉 I think/hope that also fixes this issue, but please check and report back.

**Comment by reeseovine** [comment]
It looks great, thank you very much!
