### ISSUE TITLE
Cant see any emoji

### ISSUE THREAD

**Issue by ArafatRakib** [fdw/rofimoji#20]
I tried to install it from arch repo to no avail.
Joyb pixel icon did get installed.
Then i just doenloaded the rofimoji script n run it.
But i'm shown  a list of emoji without shown any emoji icons

**Comment by fdw** [comment]
Hi @ArafatRakib, this sound like a font issue to me, similar to #13 . Can you see emoji in other applications? Which font are you using for emojis?

**Comment by ArafatRakib** [comment]
This is my fontconfig
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <match target="font">
        
        
        
        
        
        
        
        
        
        <edit mode="assign" name="antialias">
            <bool>true</bool>
        </edit>
        
        
        
    </match>

    <alias>
        <family>serif</family>
        <prefer>
            <family>DejaVu Serif</family>
            <family>Noto Color Emoji</family>
            <family>Noto Color Emoji</family>
        </prefer>
    </alias>
    <alias>
        <family>sans-serif</family>
        <prefer>
            <family>DejaVu Sans</family>
            <family>Noto Color Emoji</family>
            <family>Noto Color Emoji</family>
        </prefer>
    </alias>
    <alias>
        <family>sans</family>
        <prefer>
            <family>DejaVu Sans</family>
            <family>Noto Color Emoji</family>
            <family>Noto Color Emoji</family>
        </prefer>
    </alias>
    <alias>
        <family>monospace</family>
        <prefer>
            <family>DejaVu Sans Mono</family>
            <family>Noto Color Emoji</family>
            <family>Noto Color Emoji</family>
        </prefer>
    </alias>
    <alias>
        <family>mono</family>
        <prefer>
            <family>DejaVu Sans Mono</family>
            <family>Noto Color Emoji</family>
            <family>Noto Color Emoji</family>
        </prefer>
    </alias>

 <match target="pattern">
    <test name="prgname" qual="any">
      <string>rofi</string>
    </test>
    <edit name="family" mode="prepend_first">
      <string>Noto Color Emoji</string>
    </edit>
  </match>

   <match target="pattern">
    <test name="prgname" qual="any">
      <string>geany</string>
    </test>
    <edit name="family" mode="prepend_first">
      <string>Noto Color Emoji</string>
    </edit>
  </match>

</fontconfig>`
Do i have anything missing?

**Comment by ArafatRakib** [comment]
I tried with joypixel font also, same result

**Comment by fdw** [comment]
I could imagine that having DejaVu as the first alternative could be a problem, as that brings it own ugly emojis. Also, you defined "Noto Color Emoji" twice. Is that font installed?

My main question still stands: Can you see emojis in other applications?

Also, what distribution are you using or what are your versions of rofi and pango?

**Comment by ArafatRakib** [comment]
I've changed that config and replace every dejavu with something else.
Yes that font is installed
rofi    Version: 1.5.4
pango-1:1.44.2+1+gb50f0ef8-1
OS: Archlabs

**Comment by ArafatRakib** [comment]
![image](https://user-images.githubusercontent.com/43374810/62492182-aaac5c00-b7ef-11e9-80d0-d46e7484ec52.png)

**Comment by fdw** [comment]
Okay, that looks good.
Do emojis work in other applications? For example, can you see them [here](https://github.com/fdw/rofimoji)? Or can you see them in your text editor?

**Comment by psykotik1** [comment]
after update on arch linux can no longer see emoji either

**Comment by polyzen** [comment]
Works for me with the `noto-fonts-emoji` package.

**Comment by fdw** [comment]
But this only affects rofi? Or are all emojis gone?

What does rofi look like? Can you please upload a screenshot (`Alt+Shift+s` in rofi)?

**Comment by psykotik1** [comment]
i have that font installed but still cant see any enoy with rofimoji

**Comment by psykotik1** [comment]
![rofi-2019-08-07-0330-00000](https://user-images.githubusercontent.com/11342059/62607993-a140f380-b8c4-11e9-8f80-cf5fd3e354eb.png)
all the emoji are gone!

**Comment by fdw** [comment]
And are they gone in other applications as well?

**Comment by polyzen** [comment]
Also, are your systems fully up-to-date, and do the icons show up if you downgrade `rofimoji` to `2.1.0-1`?

**Comment by psykotik1** [comment]
system is fully up to date, downgrader doesnt list any versions of rofimoji to downgrade, so i cloned the 2.10 repo and tried that and still no emoji

**Comment by polyzen** [comment]
I don't know what downgrader is, but if it were still in your package cache, you would do:
`sudo pacman -U /var/cache/pacman/pkg/rofimoji-2.1.0-1-any.pkg.tar.xz`

**Comment by polyzen** [comment]
Alternatively: https://wiki.archlinux.org/index.php/Arch_Linux_Archive#How_to_downgrade_one_package

**Comment by psykotik1** [comment]
no, downgrading did not bring back the emoji

**Comment by psykotik1** [comment]
copying and pasting into terminal works however

**Comment by polyzen** [comment]
Perhaps one of the fonts you have installed causes conflicts or has a wonky fontconfig config?

IIRC only thing I have tweaked on my system is https://wiki.archlinux.org/index.php/Font_configuration#Disable_bitmap_fonts.

**Comment by psykotik1** [comment]
yes that must have been it, i cleared out the ~/.config/fontconfig dir and now it works, tyvm!

**Comment by ArafatRakib** [comment]
> yes that must have been it, i cleared out the ~/.config/fontconfig dir and now it works, tyvm!

Same here. but i am having another problem, Texts in polybar have become pixalated :/
![image](https://user-images.githubusercontent.com/43374810/62668509-f99ff000-b9ad-11e9-852b-bd53bed57b8e.png)
![image](https://user-images.githubusercontent.com/43374810/62668516-015f9480-b9ae-11e9-9ebb-f41a50d1e93a.png)

**Comment by polyzen** [comment]
That might be due to recent pango changes.

**Comment by ArafatRakib** [comment]
> That might be due to recent pango changes.

Do  you know any solution for this?
And though now I can see the emoji i can't use all of the emojis. Some emojis are being inserted but some are not 🤨
Thanks.

**Comment by polyzen** [comment]
On August 8, 2019 12:24:20 AM EDT, Mohammad Arafat Hossain <notifications@github.com> wrote:
> > That might be due to recent pango changes.> 
> > 
> Do  you know any solution for this?> 

I do not.

> And though now I can see the emoji i can't use all of the emojis. Some
> emojis are being inserted but some are not 🤨> 
> Thanks.> 

Could you give an example of those that don't seem to work?

> > 
> -- > 
> You are receiving this because you commented.> 
> Reply to this email directly or view it on GitHub:> 
> https://github.com/fdw/rofimoji/issues/20#issuecomment-519357469



--
Best,
Daniel <https://danielcapella.com>

**Comment by fdw** [comment]
I think this issue can be closed now.
@ArafatRakib, @psykotik1, if you still have problems, feel free to re-open.
