### ISSUE TITLE
How to change the language of the emoji keywords?

### ISSUE THREAD

**Issue by Bluey26** [fdw/rofimoji#200]
Hi, i was wondering if there is an option to change the language of the keywords used to search emojis.

By default i think this is english, but i would like to use another language instead. How can i do it?

I am using `fuzzel` as Wayland selector, and i have achieved a way to show the selector in spanish (desired language):

Opening a new terminal tab and running:

`LC_MESSAGES="es_ES.UTF-8" fuzzel`

will display the fuzzel selector with spanish language (shows common apps instaled in my system, not emojis).

Since i was wondering where the problem could be (`LC_MESSAGES="es_AR.UTF-8" rofimoji` does not change the language), i installed another wayland selector and i have encountered the same thing, the selector is shown in spanish too:

`LC_MESSAGES="es_ES.UTF-8" wofi --show=drun`

`wofi` was tested in this case.

If there is not such feature as language selection, it would be a good one.

I am using `extra/noto-fonts-emoji 1:2.042-1` as my emoji font (`OS: Archlinux`) and running in Wayland at the moment.

Package version: `rofimoji 6.4.0-1 `

**Comment by fdw** [comment]
Currently, the keywords are only available in English.

I've thought about this problem [before](https://github.com/fdw/rofimoji/discussions/109), but there was not much (no?) interest, and there's also the size question.

**Comment by Bluey26** [comment]
Oh, yes, i was thinking that the translations "scope" would be too big.

I was not sure if this was supported or not, so i decided to ask about it.

You can close the topic if you think its correct to do so, i am happy with english translations, i just need to learn or get used to the names of the emojis.

Thanks a lot for this project, it was suggested to me by another person, seems to work like a charm with fuzzel in wayland 😄

**Comment by fdw** [comment]
As an easy workaround, you can add your own keywords or descriptions with an [additional file](https://github.com/fdw/rofimoji#custom-character-files-and-descriptions).

Also, I still have the old branch and looked into it: It's possible to add translated keywords, but the names are only available in English. I don't think I'll add translation as a full-blown feature (unless there is more demand for that 😉), but maybe there is some way to make translated files available. Or a script to generate it yourself?

**Comment by Bluey26** [comment]
> As an easy workaround, you can add your own keywords or descriptions with an [additional file](https://github.com/fdw/rofimoji#custom-character-files-and-descriptions).

That's a good idea!

I just have tried it, i have downloaded `emojis_activities.csv` and modified 2 keywords, then i ran:

`rofimoji -f all emojis_activities.csv `

And my word is searchable! This seems to be a good way to allow everybody to have their own keywords, even in their own language.

I even guess this is the way to add more emojis, in case you cannot find one.

I could check them by hand, i dont think i need to translate all of them, but just a few ones.

Thanks again for your answers!

**Comment by fdw** [comment]
You're welcome! 😊

The idea behind custom files is that you can add your own characters (and if you have anything that might be interesting for others, feel free to open a PR). But if you just want to add more keywords, it's even simpler: Say you want a to append "happy" to "🙂". Then you can create a file `.local/share/rofimoji/data/emojis_smileys_emotion.additional.csv` with the line `🙂 happy`. If you use `emojis_smileys_emotion` in some way, either explicitely or implicitly, `happy` is added automatically.

More abstractly, for every file you want, `rofimoji` looks for a `<filename>.additional.csv` and merges them.
