### ISSUE TITLE
[Feature Request] All The Icons Support

### ISSUE THREAD

**Issue by julie-de-ville** [fdw/rofimoji#204]
Hello. It would be cool to see the "All The Icons" font integrated into rofimoji. I really like the software btw.

**Comment by fdw** [comment]
Hey, thank you for the kind words 😊

Do you have a link to that font?

**Comment by julie-de-ville** [comment]
https://github.com/domtronn/all-the-icons.el

**Comment by fdw** [comment]
So, let's unpack this:
- Atom File Icons: https://github.com/file-icons/icons/blob/master/charmap.md has a list that we can use
- Font Awesome is already supported 🥳
- Octicons: I haven't found a real font for this, much less a mapping between names and characters.
- Weather Icons: Maybe https://raw.githubusercontent.com/erikflowers/weather-icons/refs/heads/master/values/weathericons.xml can be used?
- Material Design Icons: See https://github.com/google/material-design-icons/issues/1566 - until that is done, there is no mapping we can use.
- All The Icons: I have found absolutely no documentation for that...

I'll see if I can add the two fonts with mappings available (unless you want to 🙂). For the others, I'd need a mapping with an appropriate license. If you know of one, please share 🙂

**Comment by fdw** [comment]
I've added support for the two icon sets that have documentation available. Can you please try it out?

**Comment by fdw** [comment]
I'm closing this issue now, but please re-open if you have something to add.
