### ISSUE TITLE
Wayland issues with XWayland

### ISSUE THREAD

**Issue by Irubataru** [fdw/rofimoji#205]
I am struggling to get this to work on Wayland for XWayland windows. It works for all other windows.

When using `action = type`, I assume it is because of this bug here https://github.com/atx/wtype/issues/62

However, I can't get `action = cliboard` to work either. In at least one of my windows, <kbd>Shift</kbd>+<kbd>Insert</kbd> does paste, but it still doesn't work. I am using `action = copy` as a workaround for now, but it would be nice to get this picker working again ^^ Not sure if there is anything you can do though.

**Comment by fdw** [comment]
Well, `Shift+Insert` is still sent using `wtype`, so if that doesn't reach XWayland windows, I don't think I can do anything about it 😕

Have you tried to send `Shift+Insert` from a command line? Does that work?

**Comment by Irubataru** [comment]
It doesn't seem like it works :(

I used this command for wtype btw

```bash
wtype -M shift -P insert -p insert -m shift
```

Not sure if it is right. It does paste in native Wayland windows, but not in XWayland ones, so I assume there is nothing to be done.

**Comment by fdw** [comment]
That does look right. Unfortunately, that's not something I can control, sorry.

If you have any idea how to improve `rofimoji` on this front, let me know!
