### ISSUE TITLE
Multiple Selector does not work on fuzzel

### ISSUE THREAD

**Issue by Linguiniotta** [fdw/rofimoji#207]
Multiple Selector with the keybind `Shift` + `Enter` does not work on fuzzel.
For example, selecting "beaming face with smiling eyes" with `Shift` + `Enter` returns random flags??? I can't screenshot fuzzel as it closes immediately, but here's the recent in rofi after selecting in fuzzel.

![image](https://github.com/user-attachments/assets/97570e65-a391-47ab-94eb-fb16063d54e5)

```
rofimoji --selector fuzzel
```

`~/.config/rojimoji.rc`
```rc
action = clipboard
max-recent = 10

skin-tone = moderate
```

**Comment by fdw** [comment]
As far as I know, `fuzzel` doesn't support multiple selections at all: https://codeberg.org/dnkl/fuzzel/issues/244

Is that outdated?

**Comment by relma2** [comment]
Multiselect doesen't work on any selector *but* rofi. Maybe update the readme file so it notes that only rofi supports the Shift+Enter thing.

**Comment by fdw** [comment]
I've made it more explicit.
