### ISSUE TITLE
Crash with NoTyperFound Exception

### ISSUE THREAD

**Issue by relma2** [fdw/rofimoji#210]
I am on Arch Linux, and I installed **rofimoji** through my package manager.

First, it did not install dependencies, which i had to remedy with `sudo pacman -S dmenu rofi fuzzel wmenu wofi wl-clipboard xsel`.

Next, when I execute `rofimoji` and pick an emoji, it crashes with a NoTyperFound Exception:
```
Traceback (most recent call last):
  File "/usr/bin/rofimoji", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/picker/__main__.py", line 9, in main
    StandaloneRofimoji().standalone()
  File "/usr/lib/python3.12/site-packages/picker/standalone.py", line 41, in standalone
    execute_action(characters, self.args.actions, self.active_window, self.args.typer, self.args.clipboarder)
  File "/usr/lib/python3.12/site-packages/picker/action.py", line 20, in execute_action
    typer.type_characters(characters, active_window)
  File "/usr/lib/python3.12/site-packages/picker/typer/noop.py", line 17, in type_characters
    raise NoTyperFoundException()
picker.typer.noop.NoTyperFoundException: Could not find a valid way to type characters. Please check the required dependencies.
```

**Comment by relma2** [comment]
Ok, I installed `wtype`, and now it gives me this error:
```
rofimoji --prompt "Emoji:" --selector fuzzel --typer wtype
Compositor does not support the virtual keyboard protocol
```

I Googled around and apparently this is an issue with wtype?

**Comment by fdw** [comment]
Let's start here:
> `sudo pacman -S dmenu rofi fuzzel wmenu wofi wl-clipboard xsel`

You don't need to install all kinds of dependencies; you need one selector and - depending on what you plan to do - one typer and/or one clipboarder. If you only plan to use the clipboard, you don't need a typer, and vice versa.

> Next, when I execute rofimoji and pick an emoji, it crashes with a NoTyperFound Exception:

Yes, because you need a typer, as you noted in next comment 🙂

> `Compositor does not support the virtual keyboard protocol`

That seems to be an error message of `wtype`: https://github.com/atx/wtype/issues/34 and thus nothing I can do about it, sorry 🫤
You could also have a look at #132, that seems to be related.

**Comment by relma2** [comment]
Yeah, Warp AI suggested I installed all those dependencies and I kind of trusted it. I can use **wl-copy**, by executing `echo 💩 | wl-copy`; so I am trying to use the "clipboard" action, which according to your documentation copies and pastes the selected emoji from the clipboard into the active window.<br />I ran:

`rofimoji --prompt "Emoji:" --selector wofi --action clipboard` 

But it still gives me "Compositor does not support the virtual keyboard protocol"

**Comment by fdw** [comment]
Guess that's one more strike against AI then 😉

As you said, `--action clipboard` will try to use the clipboard to [directly paste the character](https://github.com/fdw/rofimoji?tab=readme-ov-file#actions). To trigger the pasting, we need to send the keystrokes `Shift + Insert`, which needs a typer.

**Comment by relma2** [comment]
Yup. I found that the typer is stil run in the Clipboarder's `copy_paste_characters` method. I am trying to change it so it runs **wl-paste** instead, but I'm running into some trouble.
It doesen't work, because wl-paste writes to stdout instead of the active window.

**Comment by relma2** [comment]
Are you the one who packaged the pacman package? If so, consider adding in the dependencies to the pacman package. You can even require that the user select one of a list of tdependencies for the selector and typer and clipboarder, so they don't install ALL of them like I did.

**Comment by fdw** [comment]
> It doesen't work, because wl-paste writes to stdout instead of the active window.

Yeah, that won't work. Your best bet is to just copy to clipboard and insert manually.

> Are you the one who packaged the pacman package?

No, I'm not. Also, neither typer nor clipboarder is technically required - depending on your preferred action, you only need one.

Can I close this issue? I can't do anything about the original problem, so I think we're done, right?

**Comment by relma2** [comment]
> Can I close this issue? I can't do anything about the original problem, so I think we're done, right?
Sure. Closing.
