### ISSUE TITLE
Add support for ydotool typer

### ISSUE THREAD

**Issue by relma2** [fdw/rofimoji#211]
I want support for [ydotool](https://github.com/ReimuNotMoe/ydotool) as a "typer" in rofimoji. ydotool is a wayland equivalent of xdotool

**Comment by fdw** [comment]
I'll have a look. Or do you want to open a PR?

**Comment by relma2** [comment]
I'll have to onboard to the codebase, but I could *try* to work on it myself

**Comment by relma2** [comment]
ydotool can type ASCII characters, but still does not support emoji. Theyre working on it.

**Comment by fdw** [comment]
That's a pity, but thanks for checking it out 🙂

I'll close this ticket, but please re-open when you have new information!

**Comment by relma2** [comment]
@fdw I *think* I figured something out
1. ydotool needs a background service called ***ydotoold*** running with the socket `/run/user/1000/.ydotool_socket` enabled.
2. Then you can do stuff like `sleep 2 && ydotool type test` and it will type "test" 

ydotool does not support directly typing emojis, but you *can* type an emoji using the standard keyboard like this:
1. Hold Ctrl
2. Hold Shift
3. Type 'u'
4. type 1f642 (or the corresponding unicode code)
5. Release Ctrl
6. Release Shift
7. 🙂 

So, we would have to check if the ydotoold service is running, and if it is, convert the emoji into the unicode code we want to type and then pass that into ydotool. We can pass in separate key\_hold and key\_release events with the syntax.
For the smiley face emoji, this command is:

`ydotool key 29:1 42:1 22:1 2:1 33:1 7:1 5:1 3:1 3:0 5:0 7:0 33:0 2:0 22:0 42:0 29:0`

HOWEVER. It only works if the application being typed into does not have some other wacky keyboard shortcuts involving Ctrl and Space, like my terminal 😡. But it did work entering it into my discord.

In order for this to work, we would need to write helper scripts to convert the emoji into the unicode code and generate the ydotool command.

**Comment by relma2** [comment]
All this for an emoji picker that actually *TYPES* the emoji instead of copying it to clipboard... I am in a rabbit hole
