### ISSUE TITLE
copy_paste_emoji has race condition

### ISSUE THREAD

**Issue by andaag** [fdw/rofimoji#22]
Hi

When copying and pasting emoji on my laptop everything works fine, but when doing it on my main computer it pastes what was on my clipboard previously. This is weird because the software is identical (cloned installs, ubuntu 18.04.3), the only difference is in drivers. My main box uses nvidia drivers, the laptop intel.

When I fixed it (very cleanly and properly) by sticking in a time.sleep() after the xdotool command (https://github.com/fdw/rofimoji/blob/master/rofimoji.py#L1920) in copy_paste_emojis, things works fine.

If I don't have that sleep there in firefox it pastes whatever was in the clipboard previously. (Is xdotool queueing a command and xsel is somehow executing before it even if the .wait() is there?).

**Comment by fdw** [comment]
Interesting. What `sleep` values worked for you? Is 100ms enough?

**Comment by andaag** [comment]
I'm using 0.2, and that's not really noticeable. Since I'm doing a window change every time this happens the extra lag isn't really something I've thought about.

That said, I tried to reproduce this now on the same machine and I can't... it was however extremely easy to reproduce when I patched the script. Maybe related to number of windows open or something like that. I'll comment it out, and the next time I have a setup where I can reproduce it I'll try it with 1ms and see if that works.

**Comment by andaag** [comment]
I just ran into this one again, it's happening on a dell xps 13 with ubuntu 18.04.

a time.sleep of 0.01 was too little, but 0.05 was plenty. I recon that's small enough to not be really noticeable anyway.

**Comment by fdw** [comment]
Thank you very much for testing that!

I'll add it sometime soon-ish ;)

**Comment by fdw** [comment]
This should have been merged with #23, thanks to @chmduquesne. Can you test if it works?

**Comment by fdw** [comment]
Closing, as it should be fixed. Please re-open if you still encounter it.
