### ISSUE TITLE
Adding maths symbols

### ISSUE THREAD

**Issue by chmduquesne** [fdw/rofimoji#26]
I would love to also have maths symbols in rofimoji. If I write a PR, would you consider integrating it? I would modify `extract_emojis.py` and I would integrate https://unicode.org/Public/math/latest/MathClassEx-15.txt in there.

**Comment by fdw** [comment]
That would be quite cool, I think :)

Have you looked at the `-f` parameter? If you have a separate file with the maths symbols, it should be usable already. All that's left to do is to generate this file. If you have found a solution, I'd love to see a PR.

**Comment by chmduquesne** [comment]
In the spirit of having all in one file, I preferred to integrate the maths symbols into the emoji list. Let me know if you had something else in mind.
