### ISSUE TITLE
[Font Problem] Doesn't display certain emojis properly

### ISSUE THREAD

**Issue by Silent-Hunter** [fdw/rofimoji#28]
* What does rofimoji show instead of the emojis? Can you please share a screenshot (`Alt+Shift+s** in rofimoji) It shows a tiny black and white version of the "smiling face" and the "skull and crossbones" emojis.
* What do other apps like Firefox/Chrome/your text editor show instead of emojis? The "skull and crossbones" emoji in Vivaldi browser looks as it does in Rofimoji. But if I paste it into a page with my smartphone, and then look at that same page on my desktop, it shows the right "skull and crossbones" with color.
* Which emoji fonts do you have installed? Blobmoji.ttf
* Are the emoji fonts set in your font config? Yes
* Which versions of rofimoji and pango are installed? I just "git pull"ed the latest version of Rofimoji as of 2019-12-09 15:00 GMT-08, libpango version is 1.42.4-7~deb10u1 amd64.

![rofi-2019-12-09-1503-00000](https://user-images.githubusercontent.com/3732535/70480967-fd479e80-1a95-11ea-9d0d-8bc8e0a224d9.png)
![rofi-2019-12-09-1509-00000](https://user-images.githubusercontent.com/3732535/70480968-fd479e80-1a95-11ea-978c-2f84a94ac10a.png)

The strange thing is, this font _has_ the correct "skull and crossbones" emoji. Rofimoji just isn't using it for some reason. I suspect "smiling face" is the same but I haven't tested that.

**Comment by fdw** [comment]
Yes, that is somehow not unexpected: There are three "emojis" (smiling face, frowning face, skull and crossbones) that are actually not part of the Unicode emojis, but defined in other parts of the character map. These three are often also rendered by the usual font, for example liberation-sans. I have not yet found something I can do about this, except not use them 😉

It's a bit better described here: [https://github.com/stove-panini/fontconfig-emoji#emoji-in-common-families](https://github.com/stove-panini/fontconfig-emoji#emoji-in-common-families).
