### ISSUE TITLE
Add aliases for stantand smileys

### ISSUE THREAD

**Issue by basxto** [fdw/rofimoji#29]
:) for 🙂
:D for 😀
=D for 😃
-.- for 😑
etc.

I think those are much faster to type.

**Comment by fdw** [comment]
I agree that they are faster to write, but I don't see how to implement that in a good way: The emojis and aliases are automatically extracted from the official Unicode source. To add those shortcuts would mean to have either manual work or another source - the first method is never a good option, the second one would mean a lot of logic just for this case. And someone would have to maintain these shortcuts, too.

Do you know of a maintained list with additional aliases?

**Comment by fdw** [comment]
As there still doesn't seem to be a good, maintained list of additional annotations, I'll close this ticket. Feel free to re-open it (or a new one) if you find one.
