### ISSUE TITLE
Define rofi -padding in rofimoji.py

### ISSUE THREAD

**Issue by vredesbyyrd** [fdw/rofimoji#3]
Thanks for sharing this tool. Its the perfect solution for selecting emojis. I was using a gnome extensions before, but that takes up valuable panel space. 

I would like to define the rofi padding this script uses in rofimoji.py, so that it overrides my rofi config. I use a handful of rofi scripts, and for all but 2 I have rofi fullscreen with padding at 0, which i set in the rofi config. 

I do not know python, so I am probably doing something wrong. I tried this: 

    rofi = Popen(
        args=[
            'rofi',
            '-dmenu',
            '-padding 375',
            '-i',
            '-p',
            ' 👽   ',
            '-kb-custom-1',
            'Alt+c',
        ],
        stdin=PIPE,
        stdout=PIPE
    ) 

But rofi ignores the -padding, and just uses what is set in my config. I assume my formatting is wrong....hmmm. Any tips would be really appreciated. 

EDIT: After more use. I am going to leave the padding how it is, at 0. I found using it fullscreen make sense for how i use it. Thanks again for sharing.

**Comment by fdw** [comment]
Hi @vredesbyyrd, first, thanks for the praise 😊

Even though you mention you're okay with fullscreen, I wanted to investigate the issue 😉 Your code looks almost correct, but you have to use "375" as another entry in the list, like so:
```
   args=[
        'rofi',
        '-dmenu',
        '-padding',
        '375',
        '-i',
        '-p',
        ' 👽   ',
        '-kb-custom-1',
        'Alt+c',
    ],
```

However, I just tested this, and it doesn't work. My guess is that the [padding parameter has been deprecated](https://github.com/DaveDavenport/rofi/blob/1ab3e571eca1768d437246ca6ec09f44432b0e20/doc/rofi.1.markdown#layout) and our rofi is too new.
