### ISSUE TITLE
Allow choosing a monitor

### ISSUE THREAD

**Issue by Ooglogput** [fdw/rofimoji#30]
I only run rofi on my primary monitor, but rofimoji doesn't allow changing this. It just requires adding the `-monitor primary` option when you run rofi, substituting `primary` for whatever monitor you want it on. I already hacked it in by hardcoding it but I'm unfortunately not confident enough that I can add it as an option and submit a PR, so it would be cool if it was added.

**Comment by fdw** [comment]
Does this help:
> If you have any arguments for rofi, you can make rofimoji pass them through like this: rofimoji --rofi-args="-columns 3"

So in your case, does `rofimoji --rofi-args="-monitor primary"` work?

**Comment by Ooglogput** [comment]
Yeah sorry, I completely missed that in the docs. Thanks for the quick reply and a great piece of software!

**Comment by fdw** [comment]
You're welcome 🙂
