### ISSUE TITLE
rofimoji seriously broken with commit f211333

### ISSUE THREAD

**Issue by wimstefan** [fdw/rofimoji#31]
That's what I get when I try to run the script:
``` python
python3 src/picker/rofimoji.py
Traceback (most recent call last):
  File "src/picker/rofimoji.py", line 9, in <module>
    import configargparse
ModuleNotFoundError: No module named 'configargparse'
```
` python3 --version: Python 3.6.10 `

**Comment by fdw** [comment]
Yes, you need two new dependencies: `configargparse` and `xdg`.

Have you installed it via `setup.py`?

**Comment by wimstefan** [comment]
No I did not ... was not necessary until now ;-)
I fixed it by running `python3 setup.py build` and creating a script in `/usr/local/bin`:
```sh
#!/bin/sh
python3 $PATH_TO_ROFIMOJI.GIT/src/picker/rofimoji.py
```
That works so far but certainly is far from ideal ...

**Comment by fdw** [comment]
I think you should be able to `python setup.py install` (maybe with `--user`).

I'm also not totally happy that `rofimoji` now needs an installer, but I see no better alternatives. Do you have an idea?

**Comment by wimstefan** [comment]
Please don't misunderstand my issue! I'm very happy with this app and just wanted to report that the latest update broke things considerably. I can't come up with a solution other than I mentioned above and am glad that I got it working so far :)

So thank you very much for all your efforts to make the life of simple users more comfortable 🙏🏼

**Comment by fdw** [comment]
Sorry, I didn't want to put you on the spot 😉

I'm just always looking for ways to improve `rofimoji`, and the need for an installer is a regression, in my view. But I see no alternatives, either.

Thanks for the praise, and I hope you have fun with it 😃
