### ISSUE TITLE
Rofi-Args not working

### ISSUE THREAD

**Issue by TheJP** [fdw/rofimoji#34]
* Which versions of rofimoji? 3.0.1-1 (see screenshot)

When trying to use rofimoji with the exact same arguments as in the example on the release page (https://github.com/fdw/rofimoji/releases/tag/3.0.0) I get an error:

```bash
$ rofimoji --rofi-args "-columns 3"
usage: rofimoji [-h] [--use-clipboard] [--skin-tone {neutral,light,medium-light,moderate,dark brown,black,ask}]
                [--emoji-file FILE] [--rofi-args ROFI_ARGS]
rofimoji: error: argument --rofi-args: expected one argument
```

![2020-02-13-184631_1886x391_scrot](https://user-images.githubusercontent.com/5956390/74463342-fff9b200-4e91-11ea-9b87-dcec75b31e13.png)

Other than that it works exactly like I hoped. Cool project 👍

**Comment by fdw** [comment]
Thank you! 😊

The problem with `--rofi-args` is that the value also starts with a `-`, which confuses the argparser. I have not (yet) found a real fix, but `rofimoji --rofi-args="-columns 3"` works at least for me.
Also, with version 4.0.0 (coming very soon), you could use a config file to define this once.

**Comment by TheJP** [comment]
Thank you for the fast reply. Knowing that it was a problem with argparse I found this: https://stackoverflow.com/questions/16174992/cant-get-argparse-to-read-quoted-string-with-dashes-in-it

Using `rofimoji --rofi-args " -columns 3"` (notice the space before -columns) or `rofimoji --rofi-args="-columns 3"` both function as a workaround. The second option with the equal looks cleaner in my opinion.

**Comment by fdw** [comment]
I've added a note to the readme, but apart from that, I don't think I can do something about this 😐

**Comment by TheJP** [comment]
It's good to have it documented at least 👍
As far as I understand it, there's an open bug report in python and it might get fixed in the future.

**Comment by fdw** [comment]
Yes, there is a bug, but it has been open since 2010: https://bugs.python.org/issue9334

Thanks for finding the problem!
