### ISSUE TITLE
realloc(): invalid next size

### ISSUE THREAD

**Issue by wimstefan** [fdw/rofimoji#35]
That's the error message I get since today ... not sure what has changed since I didn't install or update rofimoji or any of it's direct dependencies (xdg and configargparse). I uninstalled and re-installed everything but the error remains. Not sure how I should proceed to get that error out of my way ...
Python 3.6.10 btw.

**Comment by fdw** [comment]
That is quite weird and sounds like a problem with maybe Python...

Do you have any more information, like where exactly it dies? How do you call `rofimoji`?

**Comment by wimstefan** [comment]
I've installed `rofimoji` with `python3 ./setup.py install --user` which puts the script in `~/.local/bin` ... I've created a key binding to invoke the script but even if I go to the terminal and run the script it just dies with only the error message you see in the title.
I invoked the script with `python3 -v ~/.local/bin/rofimoji` and catched the output in the following logfile: [rofimoji-debug-2020-04-08-17:15.log](https://github.com/fdw/rofimoji/files/4451311/rofimoji-debug-2020-04-08-17.15.log)
I hope that helps otherwise please advice me what I can do ...

**Comment by fdw** [comment]
Thank you very much, that gives some hints :)

First, I see that you're using `cpython`, is that correct? Also, it seems to me that the error pops up when you import `xdg.BaseDirectory`. Which version of `pyxdg` do you have installed?

**Comment by wimstefan** [comment]
Hmm I'm not aware of that I'm using cpython ... what would invoke that? I'm running Gentoo. Perhaps it's default behaviour?
The pyxdg version is 0.26

**Comment by fdw** [comment]
If you run `python --version`, what does it say?

**Comment by wimstefan** [comment]
> If you run `python --version`, what does it say?

`Python 3.6.10 btw`  ...

**Comment by fdw** [comment]
Can you try to download the wheel from the releases and install that?

**Comment by wimstefan** [comment]
Hmm first time I've worked with `wheel` ... ;-)
That's how I proceeded:
1. remove everything with regards to rofimoji from ~/.local/
2. download the wheel package
3. install with `wheel unpack <package>`
4. run with `python3 picker/rofimoji.py`

The result was the same error message ...
[rofimoji-debug-2020-04-08-22:12.log](https://github.com/fdw/rofimoji/files/4452603/rofimoji-debug-2020-04-08-22.12.log)

**Comment by wimstefan** [comment]
Hmm I'm a bit baffled right now 🤔
After having tried the wheel package unsuccessfully I re-installed the git sources with 'python3 ./setup.py install --user` and it works! Not sure that's because I've also updated rofi to the latest commit but I didn't think that rofi was the problem here because I could invoke it without any problems ...
In a different context I've also installed a couple of Python packages that I needed for another program to work: [rofimoji-debug.log](https://github.com/fdw/rofimoji/files/4455581/rofimoji-debug.log)

I'm closing this issue and re-open it if needed.
I want to thank you for your support and swift response all the time 🙏🏽

**Comment by fdw** [comment]
That's good to hear, and enjoy rofimoji! 🙂
