### ISSUE TITLE
Feature Request: Custom rofi prompt

### ISSUE THREAD

**Issue by facocalj** [fdw/rofimoji#36]
Currently, the rofi dmenu prompt is hardcoded as a smiley face. However, many people (me included) use custom prompts for their different rofi windows and modis.

Would there be an interest in making rofimoji's prompt customisable? If so, I could submit a PR

**Comment by fdw** [comment]
I'm definitely open to a PR. Otherwise, I'll try it myself when I find time.

**Comment by fdw** [comment]
Thanks again for your work, @facocalj!
