### ISSUE TITLE
Emojis are all of a sudden displayed as weird characters

### ISSUE THREAD

**Issue by farzadmf** [fdw/rofimoji#37]
* What does rofimoji show instead of the emojis? Can you please share a screenshot (`Alt+Shift+s** in rofimoji)

![rofi-2020-05-04-1837-00000](https://user-images.githubusercontent.com/5768792/81020325-8d67f500-8e36-11ea-8b90-a3f3e7919d51.png)

* What do other apps like Firefox/Chrome/your text editor show instead of emojis?
Emojis in other apps are fine, even when I select an emoji from `rofimoji`, it's inserted and displayed correctly in the app

* Which emoji fonts do you have installed?
Sorry, I'm not so sure about this; I have `noto-fonts-emoji`, and I think that should be fine?

* Are the emoji fonts set in your font config?
Again sorry, I don't know the answer to this one

* Which versions of rofimoji and pango are installed?
`pacman` shows `4.1.1-1` for `rofimoji` and shows `1:1.44.7+11+g73b46b04-1` for `pango`

---

I have Manjaro on my Desktop, and the confusing part for me is that everything was working fine in my environment, and I was able to see all the emojis (without me playing with font config or anything), but I recently opened `rofimoji` and I saw these weird characters appearing.

I can't say since when this happened; I'm always updating my packages, so something should have broken this, but, since I didn't configure anything before (or I did and it was a while back and I don't remember), I'm not sure what the source of the problem is

**Comment by fdw** [comment]
That definitely looks like a font problem. A good start to use better emoji fonts is this: https://github.com/stove-panini/fontconfig-emoji

**Comment by farzadmf** [comment]
Thank you @fdw for your answer. At the moment, I'm on a Windows machine, but I will try later on my Linux machine

**Comment by fdw** [comment]
Good luck! 🤞

**Comment by farzadmf** [comment]
@fdw Unfortunately, following the "tl;dr" section of the repo doesn't solve my issue :frowning_face: 

Also, I don't know if it's normal or not, but my `~/.config/fontconfig/conf.d/` directory is completely empty.

The only difference I can think of from before is that I had the Arch AUR package `nerd-fonts-complete`, and I recently removed it, do you think that would cause this issue?

**Comment by fdw** [comment]
> The only difference I can think of from before is that I had the Arch AUR package nerd-fonts-complete, and I recently removed it, do you think that would cause this issue?

No, I don't think Nerd Fonts have emojis, so this should make a difference.

> Also, I don't know if it's normal or not, but my ~/.config/fontconfig/conf.d/ directory is completely empty.

Just to be sure: Did you copy the config files from the linked repo, and maybe restarted/logged out and back in?

It seems to me like `rofi` is using the Symbola font for emojis, even though you have a better one. What font have you configured for rofi?

**Comment by farzadmf** [comment]
> Just to be sure: Did you copy the config files from the linked repo, and maybe restarted/logged out and back in?

Yes, I did what the `tl;dr` section said (copy one `69` file and one `70` file), but, to be honest, I don't remember if I restarted or not (I'm going to re-try that again in a few hours today on my Linux machine)

But, one thing I noticed (I think without a restart), we when I copied those files, all the emoji icons turned into the one where there's a rectangle with some hex inside of it; I don't know if that indicates anything

> What font have you configured for rofi?

I'm sorry, I didn't even know that we can configure a font for rofi 😝

**Comment by fdw** [comment]
> But, one thing I noticed (I think without a restart), we when I copied those files, all the emoji icons turned into the one where there's a rectangle with some hex inside of it; I don't know if that indicates anything

Okay, that sounds actually good: Now you're not using Symbola (or DejaVu? I can't remember) anymore. So all that's left is to make it use your noto font.
Can you please try `fc-cache "emoji"`?
Also, it might make sense to also copy `69-emoji-monospace.conf`, if your `rofi` uses a monospace font.

**Comment by farzadmf** [comment]
Thank you @fdw for your answer (and I appreciate you taking the time to answer 🙂 )
I'm going to try that in a few hours

**Comment by fdw** [comment]
> I tried copying the files one by one and testing each one (sorry, I'm doing them blindly, because unfortunately, I'm not sure what they do and what fontconfig generally does stuck_out_tongue_closed_eyes)

fontconfig in general defines which font is used in which place. Sometimes, only `sans` is specified, or you need to find the correct font for emojis. If you look into the files from the repo, they prohibit one bad font for emojis, and then prefer the better ones.

> I get no output when I run this command; I also tried fc-cache -v | grep emoji, but I do not get anything from there either.

Yes, because I'm an idiot. The correct command is `fc-match "emoji"`.

> Sorry if I'm being stupid here; as I mentioned above, I'm not familiar with these config files and what I need to do to properly use them
No worries, we're all learning all the time :)

**Comment by farzadmf** [comment]
> Yes, because I'm an idiot

My bad, I didn't want you to feel like that :stuck_out_tongue_closed_eyes: 

> The correct command is fc-match "emoji"

So, the output of the command is `NotoSans-Regular.ttf: "Noto Sans" "Regular"`, is it fine?

**Comment by fdw** [comment]
My output for that command is `NotoColorEmoji.ttf: "Noto Color Emoji" "Regular"`. I would guess that you don't have Noto Emoji installed or your system doesn't know about it.

As far as I know, Noto Sans doesn't contain emoji glyphs, and that would explain why they look like that in `rofi`.

**Comment by farzadmf** [comment]
So, any ideas @fdw ? I waited to be at my Linux machine to test things and reply.

So, output of `yay -Qs noto` for me is the following:
```
local/noto-fonts 20190926-4
    Google Noto TTF fonts
local/noto-fonts-emoji 20191016-6
    Google Noto emoji fonts
```

I'm assuming that means that I have proper fonts installed, but even when I open `Font Manager` and I search for `emoji`, nothing is displayed. Do you think those packages are somehow messed up, or am I missing something else? :frowning_face:

**Comment by fdw** [comment]
> I waited to be at my Linux machine to test things and reply.

Yeah, sorry, I have a feeling that we live in very different timezones.

But it seems you also have Manjaro, so I can show you my configuration:
I use `noto-fonts-emoji`, like you. In `~/.config/fontconfig.conf.d/` I have all four files from the [previously mentioned repo](https://github.com/stove-panini/fontconfig-emoji). In addition, I have `68-generic-emoji.conf` with this content:
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>

<match target="pattern">
  <test qual="any" name="family"><string>emoji</string></test>
  <edit name="family" mode="assign" binding="same"><string>Noto Color Emoji</string></edit>
</match>

</fontconfig>
```

My usual monospace font (including for rofi) is FuraCode Nerd Font.

I don't think I have any additional config.

**Comment by farzadmf** [comment]
Hey @fdw , I don't know if it's progress or not, but I, being so desperate, uninstalled the two packages and re-installed:
```bash
yay -Rns rofimoji
yay -Rns noto-fonts-emoji
yay -S rofimoji noto-fonts-emoji
```

And boom! my emojis are _almost_ back:
![rofi-2020-05-10-2222-00000](https://user-images.githubusercontent.com/5768792/81518664-c60f3f00-930c-11ea-8f1f-a7e1544e0fe4.png)

But it seems it's trying so hard to keep me disappointed :frowning_face: because, if you look, some of the emojis are still being displayed as that weird hex-rectangle.

Do you have an idea what's happening to those emojis?

**Comment by fdw** [comment]
First off, congratulations! Maybe I should start with "Have you tried to uninstall and re-install?" next time 😉

It's really interesting that you don't need a fontconfig.

Regarding the missing emojis: These should be the new ones in v13 (published this Spring) that aren't yet supported in the font. This will probably happen sometime later this year.

**Comment by farzadmf** [comment]
> First off, congratulations!
Thank you thank you 😄 

>Maybe I should start with "Have you tried to uninstall and re-install?" next time 😉
Or, maybe I should do it next time before I ask the question 😉 

> It's really interesting that you don't need a fontconfig.
Yep, I'm confused too, I think my Manjaro is too smart to need a `fontconfig` 😃 

> This will probably happen sometime later this year.
That's great to hear!

So, I guess I can close this issue, sorry for being stupid and not trying uninstall/re-install first... I thought about it, but, since I wasn't sure how everything is setup, I was worried I would break my emojis in other applications

**Comment by fdw** [comment]
> sorry for being stupid

I hope you take that back 😉 Nobody can be expected to know everything, so asking questions is the best way to learn.
It was honestly nice to solve this with you 🙂
Have fun with `rofimoji`!

**Comment by farzadmf** [comment]
> > sorry for being stupid
> 
> I hope you take that back 😉 Nobody can be expected to know everything, so asking questions is the best way to learn.

I really appreciate you saying that; not all people think like that 🙂 

> It was honestly nice to solve this with you 🙂

Wow, thank you, that makes me feel useful 😃 

> Have fun with `rofimoji`!

I _am having_ and _will have_ fun with it; it's my go-to tool for emojis 👍
