### ISSUE TITLE
Feature request: Most recent Emojis

### ISSUE THREAD

**Issue by facocalj** [fdw/rofimoji#39]
Most messaging apps keep track of the last 10-20 used emojis, for quick reference and ease of use -- something I think it would be very handy for rofimoji.
rofi itself already has that sort of functionality for its modis, it uses a cache file for keeping their command history. 

What do you think? Is this something worth giving a look into?

**Comment by fdw** [comment]
I have often thought about this, but the data management would be a lot more complex than what `rofimoji` does currently: With each call, rofi would additionally have to read a file with the frecencies, and re-order all available characters (which could be quite costly, I assume). With each decision, the frecencies would have to be updated and saved again. (That part is easy.)

In summary, I think it is an interesting feature, and I'll think some more about it.

**Comment by fdw** [comment]
As you can see, I have coded up something that kinda solves this problem, but in a very simplistic matter. Let me know if you like it 🙂

**Comment by facocalj** [comment]
Wow, that's exactly it! Super cool, man! 
I just made a minor modification with d33d4cb71b0ea4efa94c7f0d00ec548e2a96976e, for writing the emoji description/name in the _recent_ file as well. So in this way, we also speed up searching for recent emojis. 

What do you think?

**Comment by fdw** [comment]
It's a nice idea, but I decided not to include the description for several reasons that unfortunately still apply:
- Now the same characters can be listed twice, once from the recent list and once from the normal file. This will probably confuse users, but de-duplicating is probably quite costly.
- If you chose a skin tone for the emoji, you'll have two emojis with identical descriptions, but different glyphs.
- Finally, and most importantly, you can choose several characters in one go. What should the descriptions then look like? All of them? Then the combination would also show up when searching for a single emoji. Also, I have found no way to include linebreaks in the description 🙁

All in all, I see two flows for `rofimoji`:
- You want to add a character that you often use. In this case, you don't search for it, as you already know it, and can select it from the recent list. You don't need a description for it.
- You want to add something that you don't use often. For this, you can use the search function, and you don't need the recent list at all.
If this is true, then my current implementation works quite nicely. Showing the recent characters without description also separates them from the other lists.

If you have any idea how to solve the mentioned problems, I'm obviously interested 🙂

**Comment by fdw** [comment]
I changed the implementation once again 😉

I'm very interested in feedback, so please try it out!

**Comment by facocalj** [comment]
Hey man! I was tinkering on my own, but I guess you were faster :p

Okay, first things first. The last commit (d10c9c67d8a58c03c6faee9514325ee28558be90) seems to always require the presence of the `recent` file, and will throw errors complaining about the absence of the file, even if rofimoji is called without the `--max-recent argument`, or have its value set to zero. I would have expected rofimoji to just create a new blank `recent` file in case it is not available. 

Moreover, I think there is an issue in `save_characters_to_recent_file`:https://github.com/fdw/rofimoji/blob/d10c9c67d8a58c03c6faee9514325ee28558be90/picker/rofimoji.py#L278
I keep getting this error:
`File "/usr/lib/python3.7/site-packages/rofimoji-4.1.1-py3.7.egg/picker/rofimoji.py", line 278, in save_characters_to_recent_file
    max_recent = min(max_recent_from_conf, 10)
TypeError: '<' not supported between instances of 'int' and 'str'`

The `args.max_recent` variable, and consequently `max_recent_from_conf`, don't seem to be integers, which causes the type error above.

rofimoji works when converting `max_recent_from_conf` to an integer, but I am quite curious about how it should work. I can see a horizontal numbered list of emojis, but I can't select them in any way. Am I missing anything?

**Comment by facocalj** [comment]
Oh, I am stupid! The alt+number combination was a really good idea!

**Comment by fdw** [comment]
Thanks for trying it out!

> I would have expected rofimoji to just create a new blank recent file in case it is not available.

Me too, but I forgot the code 😉 Should be fixed now.

> The args.max_recent variable, and consequently max_recent_from_conf, don't seem to be integers, which causes the type error above.

Yup, I also missed that 😑

> The alt+number combination was a really good idea!

Thanks 🙂 Do you think it is obvious enough?

**Comment by facocalj** [comment]
All working good now! 
For the matter of consistency, shouldn't the number of recent emojis displayed be the same as `--max-recent`?

> Thanks slightly_smiling_face Do you think it is obvious enough?

It wasn't really obvious to me, but it is very well explained in the docs. Would it make sense to mention it in the help message?

I also wonder what should be the default behaviour, wether we should omit the recent list if `--max-recent` is set to zero or missing entirely. This way if people want the list, they would have read the docs and know how to use it.

**Comment by fdw** [comment]
> For the matter of consistency, shouldn't the number of recent emojis displayed be the same as `--max-recent`?

I thought about this too. The code is a bit more elegant currently, and you'll only notice the difference for one call after you reduced the number. After that, it's showing the correct number again.
But I guess I'll think about it some more, as it is less than ideal for the user.

> Would it make sense to mention it in the help message?

Maybe, yes.

> I also wonder what should be the default behaviour

I see where you're coming from, but I think this is a useful feature for most people, so I'd rather expose them to it by default. If they don't like it, they can turn it off, but at least they know it's there.

**Comment by facocalj** [comment]
Great, I tested your last commit and left a comment there (missing accepting max_recent as an argument), but aside from that, everything is working!

> I see where you're coming from, but I think this is a useful feature for most people, so I'd rather expose them to it by default. If they don't like it, they can turn it off, but at least they know it's there.

I am convinced!

**Comment by fdw** [comment]
Cool, thanks :)

I thought about adding it to the help output, but I'll wait for https://github.com/bw2/ConfigArgParse/issues/193 to be fixed before I work on that. Right now, it's too much of a wall of text already.

**Comment by fdw** [comment]
And it's merged
