### ISSUE TITLE
doesn't paste into qt applications

### ISSUE THREAD

**Issue by basedtho** [fdw/rofimoji#40]
examples of applications that it doesn't paste to: qutebrowser, telegram-desktop
examples of applications it does paste to (in my case): chromium, ghome-terminal

i wish i knew how to debug this. `xdotool type 👍` doesn't work either

`xdotool type literallyanywordexceptemojis` does work

**Comment by basedtho** [comment]
okay i just saw `insertion method`

**Comment by fdw** [comment]
Hi @basedtho, thanks for solving the problem yourself! I hope the workaround is acceptable 🙂
