### ISSUE TITLE
Feature Request: Gendered emojis with skin tone

### ISSUE THREAD

**Issue by facocalj** [fdw/rofimoji#41]
Some emojis have a gender modifier, e.g., shrugging and facepalm, but the current implementation of rofimoji doesn't apply the skin tone to such emojis. 

Would there be an interest in supporting that in rofimoji? 
I just finished implementing it in my fork: https://github.com/facocalj/rofimoji/commit/0539983e3027e27626037d79cc70854abd3a298e

**Comment by fdw** [comment]
Yes, please, that would be quite awesome! I can't believe I forgot that!

Do you want to open a PR?

**Comment by fdw** [comment]
Quick question regarding your commit: You assume that it is always the first character that has a skin tone. I think for 👨‍👩‍👧‍👦 etc, all of them could, right?

**Comment by facocalj** [comment]
I've just opened a PR!

> Quick question regarding your commit: You assume that it is always the first character that has a skin tone. I think for  etc, all of them could, right?

You are totally right. My current implementation seems to handle almost all  ZWJ sequences, except the family-related ones, that as you mentioned, would require the skin tone modifier after every other emoji

**Comment by fdw** [comment]
I haven't thought this totally through yet, but I think there is a generic implementation. We need to iterate through the characters and ask for every "human" emoji for the skin tone. This should work on all possible combinations.

**Comment by fdw** [comment]
So, I was curious and tried to write the generic solution. Please don't take it as an affront, I just wanted to see if it worked 🙂 I have pushed it solely that you can see it.

It's your decision whether you want to upgrade your PR or if we should merge mine. Both ways are fine for me.

**Comment by facocalj** [comment]
An affront? Nah. I'm glad to were able to find an elegant solution to fix this issue! 
I've just tested the https://github.com/fdw/rofimoji/commit/2e3e52b4a5b53342782b0c3343914e5fd8883eeb commit, it is working great! Great job!

**Comment by fdw** [comment]
Cool, thank you 🙂

So I'll merge this and push out a release 4.2.0.

**Comment by fdw** [comment]
Merged and released
