### ISSUE TITLE
Make rofimoji a modus of roji

### ISSUE THREAD

**Issue by gfarrell** [fdw/rofimoji#44]
There are many rofi plugins (e.g. rofi-calc) which can be invoked as modi within rofi. This is preferred for me, as I'm sure like many other people I have a key combination (super+d) bound to rofi, and would rather not have another one just to invoke rofimoji (and would also rather not have to open a terminal just to start it).

Would it be possible to package this in such a way as to make it a rofi modus?

**Comment by fdw** [comment]
This has been suggested and thought about before (#24), and I still like the idea, but I cannot see a reasonableway to do this. At the least, `rofimoji` would use all custom keybindings while having a higher internal complexity to keep track of stuff.

So, if you want to try or have any ideas to make it easier, I'm very open, but I'm not too hopeful, sorry.

**Comment by gfarrell** [comment]
Hmm I see. There is a rofi-emoji plugin which seems to make it work, but I guess it's a simpler tool.

**Comment by fdw** [comment]
Maybe I'll have another go at it, we'll see ;)

**Comment by fdw** [comment]
I had a go at this, and you can see the result on the [`test-mode` branch](https://github.com/fdw/rofimoji/tree/test-mode).
The code needs some polish, but I think the functionality is as good as it can get - which is to say, not ideal. From the readme:

> You cannot directly type the chosen character. You can only copy it to the clipboard.
> You can only select one character at a time.
> The custom keyboard shortcuts are still there, but mapped to Alt+Shift+1 (on a Qwerty keyboard) etc.

If you are still interested in this, please test it and give me feedback!

(also paging @farzadmf from #24)

**Comment by fdw** [comment]
Is there still interest in this? Did anyone have a look at it?

**Comment by gfarrell** [comment]
Hi @fdw -- I've been using the `rofi-emoji` plugin but I tried this:

```
git clone git@github.com:fdw/rofimoji.git
cd rofimoji
python3 setup.py build
sudo python3 setup.py install
rofi -modi "rofimoji:/home/gideon/sandbox/rofimoji/build/lib/picker/rofimoji.py" -show rofimoji
```

It works, I get a searchable list of emoji, when I hit "enter" I get a skin tone selector, but when I hit enter one more time I get this:

![rofi](https://user-images.githubusercontent.com/314331/106356763-f911bc80-62f9-11eb-9dcd-bb1089a4a951.png)

Pressing enter from here does nothing.

**Comment by fdw** [comment]
Thanks!

Apparently, I left some debugging code lying around 🤦. Please try again, it should work now.

**Comment by gfarrell** [comment]
Ok I *think* that works now!

**Comment by gfarrell** [comment]
Will you be doing an updated release so we can get it into the AUR?

**Comment by fdw** [comment]
Thank you!
The plan is to have a new release soon, but I want to have another look at the code first. Depending on how confident I am, it might first just be a RC.

**Comment by fdw** [comment]
This is now released! 🎉

**Comment by gfarrell** [comment]
🎉

—
Gideon Farrell
Cofounder / CTO
https://www.converge.io
