### ISSUE TITLE
Wheel file?

### ISSUE THREAD

**Issue by GideonWolfe** [fdw/rofimoji#46]
I am using arch, but I do not want to install from the AUR because the `rofimoji` package depends on an `emoji-font` package, which gives (in my opinion) very ugly yellow emojis.

I prefer to use the monochrome emojis that my fonts already provide since it will match my theme. I cloned the repository and I can run `rofimoji.py` in the `picker` folder and it works as expected.

However I am unable to locate any sort of `wheel` file in the releases or anywhere in the repo so I can install it in my path. How does this work? I can manually copy `rofimoji.py` to a spot in my `$PATH` (`~/.local/bin/`) but then it cannot find the symbol files.

How can install it manually?

**Comment by fdw** [comment]
There should be one linked in the releases: https://github.com/fdw/rofimoji/releases/tag/4.2.0
Does this show up for you?

**Comment by GideonWolfe** [comment]
Huh, the page you linked shows up, but I cannot for the life of me figure out how to navigate to it from the main page. Usually there is a "releases" or "packages" tab by Issues, but there is not one here.

**Comment by fdw** [comment]
That's the new GitHub design ;)
In the right bar, there's first the "about" section and then the latest release.

**Comment by GideonWolfe** [comment]
Wow, thanks for pointing that out. I love intuitive UIs!
________________________________

**Comment by GideonWolfe** [comment]
When I install the wheel, how will it know where all of the data for emojis is stored? I want to make a small CSV with specifically characters used in French, and I want to make rofimoji globally aware of this file.

If not, Is there a way I could pass it an absolute path to the csv? I plan on triggering it with a hotkey so a custom path isn't all bad.

**Comment by fdw** [comment]
The wheel file contains the csv as "data" files, so they should be stored relatively to the script. Where exactly probably depends on your system and Python.

In any case, I would recommend you do pass an absolute path to the script with the file you want. It's described in details in the [readme](https://github.com/fdw/rofimoji#options).

**Comment by polyzen** [comment]
@GideonWolfe, what monochrome emoji font do you use? Another solution would be to have that package add `provides=('emoji-font')`.
