### ISSUE TITLE
rofimoji throws error message and doesn't show any emoji

### ISSUE THREAD

**Issue by wimstefan** [fdw/rofimoji#5]
This is how the warning looks like when I press `Enter` or `Alt+c`:
```log
 Pango-WARNING **: shaping failure, expect ugly output. shape-engine='PangoFcShapeEngine', font='Noto Color Emoji 13.5', text='🏻'
```
I've compiled the latest Emoji release via Gentoo but that didn't change a thing.
Not sure how to debug and fix that? 

Please tell me what kind of information you need.

**Comment by fdw** [comment]
Okay, this is interesting - where does the warning pop up? Is this in rofi, the receiving application or a log file?
It looks like some application is not able to render the emoji.

Also, I just released v2. Maybe you want to try it and see if the error persists?

**Comment by wimstefan** [comment]
There's some progress with the latest version :)
No matter how I invoke rofimoji.py (via cmdline or my wm - awesomewm - which just spawns a shell) I still get a black surface but the error output (stderr via cmdline or errorlog from awesomewm) at least shows the icon ;-)
```log
Pango-WARNING **: shaping failure, expect ugly output. shape-engine='PangoFcShapeEngine', font='Noto Color Emoji 81.75', text='😀'
```

Please tell me what else I can provide you with to solve that little mystery ...

**Comment by wimstefan** [comment]
Hmm I guess I found the culprit via simple stupid trial & error ;-)
It is `cairo` - I had the live ebuild installed and after installing different versions of x11-libs/pango (or whatever that package is called in you distribution) I chose as next step cairo and *bang* that was it :) Now I'm back with 1.16.0 and all is working flawlessly :-D

Thank you for your swift response!

**Comment by fdw** [comment]
Thank you for finding the problem!

I hope you have fun with rofimoji 😃
