### ISSUE TITLE
Rofimoji fails to import BaseDirectory from xdg

### ISSUE THREAD

**Issue by burrhole** [fdw/rofimoji#50]
Using the latest package of rofimoji from the Arch linux repos, when calling "rofimoji", I was met with:
```
$ rofimoji
Traceback (most recent call last):
  File "/usr/bin/rofimoji", line 5, in <module>
    from picker.rofimoji import main
  File "/usr/lib/python3.8/site-packages/picker/rofimoji.py", line 12, in <module>
    from xdg import BaseDirectory
ImportError: cannot import name 'BaseDirectory' from 'xdg' (/home/burrhole/.local/lib/python3.8/site-packages/xdg/__init__.py)
```

After reinstalling `python-pyxdg-026.6` from the Arch repository, I was still getting this error. After checking [https://pypi.org/project/xdg/](url), I noticed that the issue seemed to be rofimoji trying to import the wrong modules, and after replacing 
`from xdg import BaseDirectory`
to
`from xdg import XDG_CONFIG_DIRS, XDG_DATA_HOME`
and the associated references to the new imports, the script runs as expected. 
I can understand why my fix worked, but I'm honestly not sure how the script works for others in the first place without that fix.

This is the diff of the original script vs the version that works for me:
```diff
--- rofimoji.py-bak	2020-09-23 19:33:12.850406059 -0400
+++ rofimoji.py	2020-09-23 19:37:17.411656820 -0400
@@ -9,7 +9,7 @@
 from typing import List, Tuple
 
 import configargparse
-from xdg import BaseDirectory
+from xdg import XDG_CONFIG_DIRS, XDG_DATA_HOME
 skin_tone_selectable_emojis = {'☝', '⛹', '✊', '✋', '✌', '✍', '🎅', '🏂', '🏃', '🏄', '🏇', '🏊',
                                '🏋', '🏌', '👂', '👃', '👆', '👇', '👈', '👉', '👊', '👋', '👌',
                                '👍', '👎', '👏', '👐', '👦', '👧', '👨', '👩', '👪', '👫', '👬',
@@ -73,7 +73,7 @@
     parser = configargparse.ArgumentParser(
         description='Select, insert or copy Unicode characters using rofi.',
         default_config_files=[os.path.join(directory, 'rofimoji.rc') for directory in
-                              BaseDirectory.xdg_config_dirs]
+                              XDG_CONFIG_DIRS]
     )
     parser.add_argument('--version', action='version', version='rofimoji 4.2.0')
     parser.add_argument(
@@ -189,7 +189,7 @@
 
 def load_recent_characters(max: int) -> List[str]:
     try:
-        with open(os.path.join(BaseDirectory.xdg_data_home, 'rofimoji', 'recent'), 'r') as file:
+        with open(os.path.join(XDG_DATA_HOME, 'rofimoji', 'recent'), 'r') as file:
             return file.read().strip().split('\n')[:max]
     except FileNotFoundError:
         return []
@@ -286,8 +286,8 @@
 
 
 def save_characters_to_recent_file(characters: str, max_recent_from_conf: int):
-    old_file_name = os.path.join(BaseDirectory.xdg_data_home, 'rofimoji', 'recent')
-    new_file_name = os.path.join(BaseDirectory.xdg_data_home, 'rofimoji', 'recent_temp')
+    old_file_name = os.path.join(XDG_DATA_HOME, 'rofimoji', 'recent')
+    new_file_name = os.path.join(XDG_DATA_HOME, 'rofimoji', 'recent_temp')
 
     max_recent = min(max_recent_from_conf, 10)
 
@@ -314,7 +314,7 @@
 
 
 def append_to_favorites_file(characters: str):
-    file_name = os.path.join(BaseDirectory.xdg_data_home, 'rofimoji', 'favorites')
+    file_name = os.path.join(XDG_DATA_HOME, 'rofimoji', 'favorites')
 
     os.makedirs(os.path.dirname(file_name), exist_ok=True)
     with open(file_name, 'a+') as file:
```

Apologies if there's anything confusing or poorly formatted in this issue.

EDIT: Also, after looking at the XDG Base Directory specification at [https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables](url) it looks like rofimoji should be importing `XDG_CONFIG_HOME` rather than `XDG_CONFIG_DIRS` for `$HOME/.config/rofimoji.rc` since `HOME` defaults to `$HOME/.config/` and `DIRS` defaults to `/etc/xdg`, but I may be mistaken.

**Comment by fdw** [comment]
That is something... I also have the Arch package installed, and it works fine for me, so it's not a systematic error. I think the problem is basically that there are two libraries in Python that provide xdg dirs functionality: [pyxdg](https://freedesktop.org/wiki/Software/pyxdg/), installable in Arch with python-pyxdg, and [xdg](https://github.com/srstevenson/xdg), which is not packaged in Arch. `rofimoji` uses the former.
Unfortunately, both provide a `from xdg import [...]`. I guess you have manually installed the other one, xdg, and it now interferes with the one `rofimoji` needs.
That's a really dumb problem, but I don't think I can do anything about it.

Regarding the difference between `XDG_CONFIG_HOME` and `XDG_CONFIG_DIRS`: You are right in what they do, but I think it doesn't hurt that you can specify a system-wide config for `rofimoji`. Do you disagree?

**Comment by burrhole** [comment]
Thank you for the quick reply! After checking pip it turns out that you're absolutely correct, it was the conflicting xdg libraries causing the issue. Not sure how that got in there... After removing the `xdg` package the original script works the way it should 😀.

Your reasoning for using `XDG_CONFIG_DIRS` makes total sense, thank you for explaining it. To be honest I wasn't exactly sure how the two were related.

Have a nice day!

**Comment by fdw** [comment]
No worries, I'm happy to help! Hope you enjoy `rofimoji` 🙂
