### ISSUE TITLE
How to use most recently used list?

### ISSUE THREAD

**Issue by farzadmf** [fdw/rofimoji#52]
Hello,

Quick question about using the most recently used list. According to the README, I should be able to use `Alt+<number>` to insert the corresponding emoji, but when I press the combination `Alt+<number>`, nothing happens and `rofimoji` is closed without inserting anything.

Is there an additional setting I need to configure?

Thank you

**Comment by fdw** [comment]
Recently used emoji are inserted using your default insertion method. This might not work for some applications, for example Firefox doesn't accept typing emojis.

Depending on your applications, you could try out either `--insert-with-clipboard` or `--copy-only`.

**Comment by fdw** [comment]
No, it should call the same exact code 🤔

Do you have any configuration or parameters set? Can you please call `rofimoji` from the terminal and see if an error pops up when you use the MRU list?

**Comment by farzadmf** [comment]
That's a very good idea @fdw , I will get back to you on that one because right now, I'm not at my Linux computer.

I'm gonna try later today and let you know 🙂

**Comment by farzadmf** [comment]
Hey @fdw , so I'm back to my Linux machine, and I'm trying these:
- Insert by search and pressing enter: 🙂
- Insert using `Alt+1`:  (as you see nothing was inserted)

When I run my command `rofimoji --rofi-args '-theme purple -columns 3'` inside the terminal (or use the shortcut I've assigned to it), the emoji is inserted no matter which method I use (MRU list or pressing `ENTER`)

However, I see something interesting happening: in here (when writing this reply), if I press `Win+<1..0>`, it seems that it's inserting the first 10 emojis in the list (but I think that's different than the MRU one)

**Comment by fdw** [comment]
Which browser do you use? Can you please try other applications, too?

**Comment by farzadmf** [comment]
Hi @fdw , I'm using Chrome

For the sake of testing, I tried opening GIMP, and normal way using `enter` works and emojis are inserted, but the `alt+<number>` doesn't work.

Inserting emojis directly in the terminal is fine (both the `enter` way and the `alt` way)

**Comment by fdw** [comment]
Sorry, @farzadmf, somehow this issue totally slipped my mind.

I just pushed something to the branch `feature/action` that refactors the insertion a bit, but should not fundamentally change it. However, maybe it works for you 🤞

**Comment by farzadmf** [comment]
No worries @fdw and thank you for the update :slightly_smiling_face: 

Just a quick question: do I need to do something to have those changes, or they're gonna be reflected in the Arch package?

**Comment by fdw** [comment]
No, these are just some experimental changes. Maybe they will be added to the next version, but there are absolutely no plans for that so far.

If you want to try it, you can check out the repo and install this version with `python setup.py install` (ideally in a venv).

**Comment by fdw** [comment]
I assume it works now, and close this ticket. Feel free to re-open if you have problems.

**Comment by farzadmf** [comment]
Yup, sorry @fdw , my bad, I forgot to close the issue
