### ISSUE TITLE
Add support for wofi

### ISSUE THREAD

**Issue by ryzokuken** [fdw/rofimoji#53]
I know this makes a tad less sense, but hear my out.

I'm a big fan of the project, and used to swear by it on X11. But ever since I switched to Wayland, I've been using `wofi` instead of `rofi`, for various reasons and that makes it infeasible to use this package.

It would be great if you allowed manually specifying the dmenu provider so I could swap out `rofi -dmenu` for `wofi --dmenu`.

**Comment by fdw** [comment]
Interesting idea 🙂

I'll think about it, but first some questions: Are the APIs otherwise identical between `wofi` and `rofi`? Do custom shortcuts work the same way? If not, this is a way larger problem...

Otherwise, with the recent release of `rofi` 1.6.0, a `rofimoji` modi maybe became feasable. I'd like to look into this, but I haven't yet found the time. But this could also solve this problem, I think.

**Comment by ryzokuken** [comment]
`wofi` aims to be compatible as much as possible IIUC, so it shouldn't be too bad, but we could definitely look into it deeper.

**Comment by fdw** [comment]
Would a rofi "mode" be helpful for you? If so, maybe you could have a look at #44.

**Comment by ryzokuken** [comment]
I don't think so, modes are specific to rofi, while here I'm suggesting a `dmenu` mode that can be fed into any `dmenu` compatible launcher, including both rofi and wofi.

**Comment by fdw** [comment]
Ah, okay :)

Unfortunately, I don't have Wayland or `wofi` running, so I can't really test it. Could someone help with that? I've prepared a [branch](https://github.com/fdw/rofimoji/tree/wofi) where `wofi` is called, without any other changes. Does that work?

**Comment by ryzokuken** [comment]
@fdw I can certainly help with that. I'll try to build that branch early tomorrow morning. It should fail, but I will make a PR to fix the rest :D

**Comment by fdw** [comment]
Thanks :) There's two calls to `rofi` (or now `wofi`) in it, and I would like to see which parameters work and which don't. Depending on how compatible it is, the solution could be quite easy.

**Comment by fdw** [comment]
I've pushed something new to the branch. I think it should work already 😁 But please test it and report any bugs or ideas you have.

**Comment by fdw** [comment]
Have you had any chance to test the branch?

**Comment by ryzokuken** [comment]
@fdw oops, no, I'm back to work but I'll try this weekend.

**Comment by fdw** [comment]
Thank you, and please don't stress yourself 🙂

**Comment by fdw** [comment]
Did you (or someone else) have a chance yet to look at it? If possible, I'd like to merge it soon and probably release a new version.

**Comment by heyLu** [comment]
I did today!  Only tried very simple usage, i.e. just running rofimoji and pasting into various applications.  That worked well.

I also tried `alt+c` which did not work for me, but I also don't have much experience with that.

Here's how it looks on my system:

![2021-02-06T22:51:48,928560147+01:00](https://user-images.githubusercontent.com/527119/107130483-24824180-68ce-11eb-9486-88c77dd65eb7.png)

@fdw, thanks for implementing this!

---

For anyone interested, here's my modification to `rofimoji-git` [from the AUR](https://aur.archlinux.org/packages/rofimoji-git/):

```diff
diff --git a/PKGBUILD b/PKGBUILD
index 97ac6a4..f1f2c42 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -1,13 +1,13 @@
 # Maintainer: Daniel M. Capella <polyzen@archlinux.org>
 
 pkgname=rofimoji-git
-pkgver=4.3.0.r28.g4247a27
+pkgver=4.3.0.r40.gc2eb151
 pkgrel=1
 pkgdesc='Character picker for rofi'
 arch=('any')
 url=https://github.com/fdw/rofimoji
 license=('MIT')
-depends=('emoji-font' 'python-configargparse' 'rofi')
+depends=('emoji-font' 'python-configargparse' 'wofi')
 makedepends=('git' 'python-pip' 'python-setuptools' 'python-wheel')
 optdepends=('nerd-fonts: for the Nerd Fonts character file'
             'wl-copy: for the Wayland clipboarder'
@@ -18,7 +18,7 @@ optdepends=('nerd-fonts: for the Nerd Fonts character file'
 provides=('rofimoji')
 conflicts=('rofimoji')
 install=$pkgname.install
-source=("git+$url.git")
+source=("git+$url.git#branch=wofi")
 b2sums=('SKIP')
 
 pkgver() {
```

**Comment by fdw** [comment]
Thanks for trying it out!

> I also tried alt+c which did not work for me, but I also don't have much experience with that.

I don't think that `wofi` supports custom keybindings, unfortunately.

I've just merged the branch and released a second RC.

**Comment by ryzokuken** [comment]
Thanks @fdw and @heyLu! I didn't have enough time to test more, but I'd install it and get it running.

**Comment by fdw** [comment]
This is now also released! 🎉

**Comment by treeshateorcs** [comment]
any idea why it outputs squares into qutebrowser?  - these three line looks like this

![image](https://user-images.githubusercontent.com/60894565/110173522-05a89980-7dff-11eb-94c8-7e132882da98.png)

**Comment by fdw** [comment]
It might be that qutebrowser, like Firefox, has trouble accepting emojis as input. I guess you are using wofi? Have you tried to set `--action copy` or `--action clipboard`?

**Comment by treeshateorcs** [comment]
oh, wow thank you! it works with `--action clipboard`
