### ISSUE TITLE
Suggestion: provide a man page

### ISSUE THREAD

**Issue by Flurrywinde** [fdw/rofimoji#57]
I like this tool a lot, but I know I'll forget the keybinds. Thus, I made a man page for myself and thought I'd share it. [rofimoji-manpage.zip](https://github.com/fdw/rofimoji/files/5625915/rofimoji-manpage.zip)

Here's the command I use to make the man page from the markdown file: 

`pandoc -s -t man -o <output.1> <input.1.md>`

On my system (Ubuntu 18.04), I put my custom man files here: `~/.local/share/man/man1`

**Comment by fdw** [comment]
I'm all for having a manpage and tried it before, but there doesn't seem to be a way to include it in the wheel file.

@polyzen, do you know of a good way to provide the man page?

**Comment by polyzen** [comment]
https://packaging.python.org/guides/distributing-packages-using-setuptools/#data-files

Eg. https://github.com/thp/urlwatch/blob/44e862282d39a6e23f67c3c0240a93cccbb41a55/setup.py#L26

**Comment by fdw** [comment]
Cool, thank you very much.

I'll have a look when I have some free time - hopefully soon 🙂

**Comment by fdw** [comment]
Please have a look :)

**Comment by Flurrywinde** [comment]
Awesome! Glad to be of help, and it helps me too to learn how to add man pages to a setup.py.
