### ISSUE TITLE
Sorting: Always display exact matches first

### ISSUE THREAD

**Issue by rixx** [fdw/rofimoji#59]
The new aliases (which are really neat, by the way) sometimes require keyboard interaction even when you type in an exact match. Eg when you type "rocket" (which is a full emoji name), you will still get "astronaut (astronaut, rocket)" as first result.

As a side note, it might be nice not to show the original name in brackets, too, because some of the entries get pretty long.

**Comment by fdw** [comment]
I don't think I can do anything about the matching; rofi does the filtering and I don't think I can tell it to prefer some words over others. If anyone has an idea, though, I'm open :)

I'll see what I can do about removing the name from the annotations. That seems possible, at least ;)

**Comment by fdw** [comment]
The second part was fixed 🙂

If someone has an idea how to fix the order, I'd be grateful.

**Comment by fdw** [comment]
That was almost embarrassingly easy: rofi has a `-sort` flag to sort the results by some measure (the Levenshtein distance by default). So this should be fixed.
