### ISSUE TITLE
rofimoji only copies one emoji to clipboard

### ISSUE THREAD

**Issue by rixx** [fdw/rofimoji#6]
When selecting multiple emoji, only one emoji is copied to my clipboard – It seems you're copying each emoji individually, overriding the previously copied emoji.

**Comment by fdw** [comment]
Hi @rixx, you're right, that couldn't have worked. Why did I do this? 🤦‍♂️

I pushed a fix to `fix/copy-multiple`. I think it works now, but it would be nice if you could also check before I merge. Thank you!

**Comment by rixx** [comment]
Looks good to me, thank you!

**Comment by fdw** [comment]
Thank you!

Merged & published.

**Comment by HaleTom** [comment]
For Googlers, try pressing Shift+Enter to copy multiple emojis :)
