### ISSUE TITLE
Insert into another Rofi window

### ISSUE THREAD

**Issue by JustinLovinger** [fdw/rofimoji#60]
Is is possible to use Rofimoji to insert Unicode into another Rofi window? I setup a Rofi menu to create named Sway workspaces, with the intention of adding emoji names, only to discover that the Rofimoji menu will not show up while another Rofi menu is open.

**Comment by fdw** [comment]
I don't think you can have two rofi windows open. You could maybe ask over at https://github.com/davatorium/rofi, if you want.

As a workaround, you could copy the emojis to the clipboard and paste them into the other rofi window. I agree that that's not ideal, though.

**Comment by JustinLovinger** [comment]
I made an issue with Rofi itself: <https://github.com/davatorium/rofi/issues/1232>.
