### ISSUE TITLE
--action argument is unrecognized

### ISSUE THREAD

**Issue by etiago** [fdw/rofimoji#61]
Using the latest package in Arch's pacman (v.4.3.0), I get the following:

```
rofimoji --action=type
usage: rofimoji [-h] [--version] [--insert-with-clipboard] [--copy-only] [--skin-tone {neutral,light,medium-light,moderate,dark brown,black,ask}] [--files FILE [FILE ...]]
                [--prompt PROMPT] [--rofi-args ROFI_ARGS] [--max-recent MAX_RECENT] [--clipboarder CLIPBOARDER] [--typer TYPER]
rofimoji: error: unrecognized arguments: --action=type
```

And I see that the latest change concerns actions. Could a regression have been introduced?

**Comment by fdw** [comment]
On the contrary, the `action` parameter is new and not yet released. With 4.3.0, you probably want `--type` (which is also the default).

Here's the readme for 4.3.0: https://github.com/fdw/rofimoji/blob/1ad0742d4d8536a1e0538163c9d2676495061440/README.md

**Comment by etiago** [comment]
Aha! My bad then, sorry! :bow:

**Comment by fdw** [comment]
No worries 🙂 Maybe I should write the version in the readme.
