### ISSUE TITLE
Firefox issue tracked in Bugzilla

### ISSUE THREAD

**Issue by katacarbix** [fdw/rofimoji#63]
https://bugzilla.mozilla.org/show_bug.cgi?id=1657777

Not sure where else I should put this but last night I stumbled across the bug report that would solve the issue of rofimoji not being able to use `xdotool type` in Firefox. It's a good issue to follow and vote for if you'd benefit from it being fixed.

**Comment by fdw** [comment]
I've started a [discussion](https://github.com/fdw/rofimoji/discussions/66) on this, since I don't want to keep issues open, and I wanted to try that feature anyways 😉
