### ISSUE TITLE
No output in X windows

### ISSUE THREAD

**Issue by rixx** [fdw/rofimoji#7]
No matter how I start rofimoji, upon hitting enter I get no output. Copying with Alt+c works fine, though. xdotool is installed and confirmed as working – are there any other troubleshooting steps I could take?

**Comment by fdw** [comment]
If I understand you correctly, you can use `xdotool` to write to the problematic windows, but rofimoji can't. Correct?

I had some look with varying (esp increasing) the sleep delay before `xdotool` is called. Does that help?

**Comment by rixx** [comment]
The delay doesn't figure into it, sadly. Adding a print(emoji) verifies that the emoji is correct and rofimoji runs the correct branch.

If I step into ``pdb``

- ``Popen(args=['xdotool','type','--clearmodifiers', 'foo'])`` prints ``foo``
- ``Popen(args=['xdotool','type','--clearmodifiers', emoji])`` doesn't print the emoji although it is definitely present (``print(emoji)``) shows it correctly
- ``Popen(args=['xdotool','type','--clearmodifiers', emoji + 'foo'])`` prints ``foo`` without invisible spaces or unprintable characters.

So I figure this has to be an encoding issue when interfacing with xdotool. Running ``xdotool type --clearmodifiers 😀`` from the command line doesn't work either in my standard terminal (terminator, a gnome-terminal clone), but it *does* work in rxvt-unicode and xterm.

What I can't figure out is why it would work in some terminals, not in others, and not when started via i3, either. I'm running standard Arch with standard X (``xdotool version 3.20160805.1``).

**Comment by fdw** [comment]
Unfortunately, I'm running out of ideas. Kitty is the only application where this happens, but it can paste emojis from the clipboard (so it's not a font issue). `xev` shows that `xdotool` types the correct emoji, so I don't think there's a problem with `xdotool`, either. Encodings other than `utf-8` don't make any sense.

**Comment by rixx** [comment]
The thing is that I don't get any output on, say, Firefox windows, either. Could it be an i3 issue in how xdotool is started?

**Comment by fdw** [comment]
I also use i3 (as you could probably guess), and it works fine for me. My configuration is: `bindsym $mod+e exec "rofimoji"`. With this, I can type into Firefox (but it needs a bit of delay to work), GTK applications, LibreOffice and so on.

Which Python version do you use? Which i3?

**Comment by rixx** [comment]
- ``i3 version 4.16 (2018-11-04) © 2009 Michael Stapelberg and contributors``
- ``Python 3.7.2``
- ``bindsym $mod+m exec rofimoji`` (quoting makes no difference, though)

Any difference to your setup?

**Comment by fdw** [comment]
Nope, I have exactly the same versions 🤔
Grasping for straws: Do you compton? Anything else that might interfere?

**Comment by rixx** [comment]
No compton or anything else. I start i3 via ``startx`` in my ``zshrc``, and then ``exec i3`` in my ``xinitrc``, run directly in tty0 after startup. It's pretty bare-bones.

**Comment by fdw** [comment]
Well, at least that's a difference ;) I start it from lightdm. But I can't imagine that being the problem.

**Comment by fdw** [comment]
One more question: Do you use any other rofi script with xdotool, for example [rofi-pass](https://github.com/carnager/rofi-pass)? Does that work?

**Comment by fdw** [comment]
Yes, it is. Somewhat expectedly, it's the same whether I try rofimoji or rofi-pass. So it seems that something else is the problem.
Are other UTF-8 characters a problem?
Do you have a `$LANG` environment var set? Does it contain `utf-8`?

**Comment by rixx** [comment]
```
echo $LANG 
en_GB.UTF-8
```

I'm kind of out of ideas here.

**Comment by fdw** [comment]
This is really strange. I have no clue what the difference between "started by i3" and "started in uxrvt" could be. Both are supposed to use the same settings.

Right now I can't think of anything that might help. I'm sorry.

**Comment by Epse** [comment]
I have a similar problem with qutebrowser.. Also i3, python 3.7.2 and xdotool can type letters into my window just fine, but no emoji. No error message either.

**Comment by Epse** [comment]
Ah great, now qutebrowser crashes when I manually use xdotool

**Comment by fdw** [comment]
Do you have anything unusual about your setup, @Epse? Do you use `startx` or lightdm?

I think it might also make sense to open up an issue over at [xdotool](https://github.com/jordansissel/xdotool/issues), maybe they have some more ideas or insights.

**Comment by fdw** [comment]
As there is no new information in any way, I'll close this ticket. Feel free to re-open if you have something interesting to add 🙂

**Comment by rixx** [comment]
So the issue doesn't exist for anybody except me anymore? Ok, good to know!

**Comment by fdw** [comment]
I'm truly sorry that it still doesn't work, but I haven't heard from anybody else or found new information.

I don't know what differences there are between terminals and i3 apart from env variables, and I'm quite sure there is no `$DISABLE_ROFIMOJI=true` 😉

**Comment by fdw** [comment]
@rixx @Epse : Could you please try #15? It's a bit of a hack, but if it improves things, I can merge it.

**Comment by rixx** [comment]
Seems to work for me! 😅🥳

**Comment by fdw** [comment]
Cool. I think this will be the next release then 🙂
