### ISSUE TITLE
--action expected one argument despite working correctly

### ISSUE THREAD

**Issue by Gelio** [fdw/rofimoji#72]
Hey, thanks for this great project :smile: 

I encountered a minor problem when running rofimoji. I run it using the following command:

```sh
./rofimoji.py --action copy
```

and it works fine - rofi appears with the emojis, and I can select some, which is then copied to the clipboard. However, after rofi closes, the following is printed to the console:

```
usage: rofimoji.py [-h] [--version] [--action {type,copy,clipboard,unicode,copy-unicode}]
                   [--skin-tone {neutral,light,medium-light,moderate,dark brown,black,ask}]
                   [--files FILE [FILE ...]] [--prompt PROMPT] [--rofi-args ROFI_ARGS]
                   [--max-recent MAX_RECENT] [--clipboarder {xsel,xclip,wl-copy}]
                   [--typer {xdotool,wtype}]
rofimoji.py: error: argument --action/-a: expected one argument
```

which is puzzling, since I did provide an argument :smile:

That's not a problem, since the application works fine. It may be misleading, though :slightly_smiling_face:

**Comment by fdw** [comment]
Thanks for your kind words and for trying out the RC version!

The bug should be fixed now 🙂

**Comment by Gelio** [comment]
That was fast! The issue is gone, thanks :slightly_smiling_face:
