### ISSUE TITLE
Can I get emoji output with stdout?

### ISSUE THREAD

**Issue by Riey** [fdw/rofimoji#75]
Hi good to see this cool project :+1:  I want use rofimoji output in my library(It's IME called [kime](https://github.com/Riey/kime))

so I spawn rofimoji process in code and works nice but as README mentioned, xdotool and wtype is not working on some apps

however, if rofimoji support stdout output such as `--action stdout` I can use IME side `commit string` for those apps

**Comment by fdw** [comment]
It should be possible to make `rofimoji` output the chosen characters to `stdout`.

However, I'd like to understand your usecase a bit better - maybe we can even find something that fits better 🙂
If I understand you right, you want to call `rofimoji` from your `kime`, including the `rofi` window, and then take that selection and do something with it, right? Or would you also like to forgo the `rofi` window?

**Comment by Riey** [comment]
> If I understand you right, you want to call rofimoji from your kime, including the rofi window, and then take that selection and do something with it, right? Or would you also like to forgo the rofi window?

Yes exactly maybe I'll want without `rofi` mode later(for better integrated ui) but now I just want spawn `rofi` window and read `rofimoji` output then commit it via IME method

**Comment by fdw** [comment]
You can try the latest `main` branch 🙂

**Comment by Riey** [comment]
I tried `main` and works great :+1: have you plan for next release?

![20210307154852](https://user-images.githubusercontent.com/14910534/110231702-a6609b80-7f5c-11eb-8dfa-d9109406cc97.png)

**Comment by fdw** [comment]
No, I don't have a plan for the next release yet. I'd like to wait a bit more if there's any other new features, if that's alright with you.

**Comment by Riey** [comment]
Then I'll wait for those new features, may I close this issue or would you close when new release is published?

**Comment by fdw** [comment]
I'll close it now, the next release will happen anyway 😉
