### ISSUE TITLE
rofi in -modi mode is blank

### ISSUE THREAD

**Issue by laur89** [fdw/rofimoji#76]
Rofi runs fine when executed by `rofimoji`. Yet when `rofi -modi "emoji:rofimoji" -show emoji` is ran, then empty rofi dialog is displayed. No errors, just empty rofi window.

Rofi config:

```
! ------------------------------------------------------------------------------
! ROFI Color theme
! ------------------------------------------------------------------------------
rofi.color-enabled: true
rofi.font: Droid Sans Mono for Powerline 10
rofi.theme: gruvbox-dark-hard
rofi.terminal: urxvtc
rofi.show-icons: true
!rofi.matching: regex
rofi.bw: 3
```

Bit unrelated, but is there also possible to combine rofi with other pre-existing combi options?
Eg

```rofi -show combi -combi-modi 'window#drun#run' -modi combi#ssh -modi emoji#rofimoji  -sidebar-mode```

produces no errors, but only the `combi` and `ssh` modes are displayed.

Rofimoji installed by `/usr/bin/env python3 -m pip install --user --upgrade git+ssh://git@github.com/fdw/rofimoji.git`

**Comment by fdw** [comment]
Could you please tell me which versions of `rofimoji` and `rofi` you are using?

> Bit unrelated, but is there also possible to combine rofi with other pre-existing combi options?
Yup, it should. It could either be related to the previous problem, or you need to define your modi in one command, like `-modi combi,ssh,emoji:rofimoji`

**Comment by laur89** [comment]
Rofi `1.5.4`
rofimoji `5.0.0`

**Comment by fdw** [comment]
I fear I have bad news for you: `rofimoji` as a mode only works on `rofi` 1.6.0 and later 🙁

**Comment by laur89** [comment]
Ah that explains it. Maybe mention it in Readme to avoid future tickets like this?

I'll try to find who's  the maintainer of debian package and see if newer version can be published.

Thanks, closing.

**Comment by fdw** [comment]
> Maybe mention it in Readme to avoid future tickets like this?

That's a good idea, thanks! I've just added a sentence.
