### ISSUE TITLE
Can't copy "skin-emojis" to clipboard

### ISSUE THREAD

**Issue by AckslD** [fdw/rofimoji#77]
If an emoji has multiple skins such as 👍 then after selecting the emoji and I'm prompt to choose the skin I cannot use `alt+c` to copy to clipboard anymore, it just types `c` in the search field.

**Comment by fdw** [comment]
You need to select the action in the first selection window.

If you could select the action later, that would be a problem if you selected multiple characters, for example.

**Comment by AckslD** [comment]
Ah I see! Thanks @fdw :)
