### ISSUE TITLE
Usage in rofi freezes Xorg

### ISSUE THREAD

**Issue by samhh** [fdw/rofimoji#79]
Repro:

1. Run `rofi -modi "emoji:rofimoji -a copy" -show emoji`
2. Select any emoji with the Enter key
3. Everything bar the mouse will be frozen - need to switch to another TTY to kill rofi

This doesn't occur if I run `rofimoji -a copy`, nor does it occur if I omit the `-a copy`. It doesn't make a difference if I specify a `--clipboarder`, and I've been using rofi for a long time with other "modi" without issue.

I'm on Arch with everything up to date. rofimoji is v5.0.0.

**Comment by fdw** [comment]
That sounds interesting. Which `clipboarder` did you choose, and which ones have you installed? And are you on X or Wayland?

**Comment by samhh** [comment]
I'm on X.

I tried `--clipboarder xclip` and I tried omitting it. I don't have xsel installed, but xclip certainly is and does work if invoked directly.

**Comment by fdw** [comment]
Thanks. Unfortunately, I have several more questions:
* Did you select an emoji that needed a skin tone?
* After you killed `rofi`, can you find a file `$XDG_CACHE_HOME/rofimoji` (or `~/.cache/rofimoji`)?
* Is it saved in the `$XDG_DATA_HOME/rofimoji/recent` file (if you allow that)?

**Comment by samhh** [comment]
1. Same issue occurs selecting a flag emoji.
2. Nope, `~/.cache/rofimoji/` doesn't exist (and if it's relevant I don't have appear to have an `$XDG_CACHE_HOME` set).
3. Yes, I can see it both there and in the "recents" area on subsequent execution.

**Comment by fdw** [comment]
Okay, that was a very weird bug. I could reproduce it, and it seems to be a common problem with using `xclip`.
Can you test the latest `main` branch and see if it works?

**Comment by samhh** [comment]
Success, fixed! :confetti_ball:
