### ISSUE TITLE
Don't recommend yaourt as an AUR helper

### ISSUE THREAD

**Issue by hashworks** [fdw/rofimoji#8]
As you can see in this [comparison table](https://wiki.archlinux.org/index.php/AUR_helpers#Comparison_table) `yaourt` really shouldn't be used anymore. Even the author implicitly abandoned the project ("I do not plan to maintain yaourt anymore. The codebase is old, in bash, have implementations issues and other aur helper have superseded it these last years. Maybe it's time for yaourt to retire to the attic?").

**Comment by fdw** [comment]
While I wouldn't say that the readme could be seen as a recommendation, I agree that we shouldn't mention yaourt explicitely. The new solution is more generic 😉
