### ISSUE TITLE
Character insertion frequently fails

### ISSUE THREAD

**Issue by gfarrell** [fdw/rofimoji#83]
I use rofimoji as a standalone thing called from rofi (open rofi -> type emoji -> open rofimoji), and about 90% of the time hitting enter on an emoji does not result in it being inserted into whatever text field etc. I'm working in. It sporadically works, but most of the time I have to copy and paste the character.

I'm really unsure how to go about debugging this though, so am happy to do so with some pointers to gather more information. I notice this the most in firefox because I spend so much time in it.

**Comment by fdw** [comment]
The problems with Firefox are documented [here](https://github.com/fdw/rofimoji#insertion-method) and [here](https://github.com/fdw/rofimoji/discussions/66). There's nothing I can do about it.

Do you notice any other problems?

**Comment by gfarrell** [comment]
Ah sorry @fdw I didn't realise. I'll just switch to copy mode for now. I can't say for sure if I've experienced it anywhere else but if I do I'll let you know and close this for now.

**Comment by fdw** [comment]
No worries, it's an annoying problem :(

Hope it works better for you!

**Comment by sixtyfive** [comment]
Enter does nothing for me. Alt+P works after 5-10 seconds, but then X is completely blocked until Alt+Tab is used. Alt+T again does nothing. Using Solus which uses Budgie. All of rofi, xdotool, xsel and xclip are installed. Is there a way to debug what's going on there?

**Comment by fdw** [comment]
First, can you please open a new issue for this? It sounds quite unrelated.

Secondly, which version of `rofimoji` do you have? And have you tried to run `xdotool` or `xsel` from the terminal? Does that work without problems?
