### ISSUE TITLE
Feature request: custom keybindings

### ISSUE THREAD

**Issue by DMBuce** [fdw/rofimoji#84]
As an example of how this would be useful, Alt+c copies emoji regardless of the `--action` flag. It would be nice to be able to use Control+c instead.

Since rofi seems to use the first argument if it's passed two of the same option, a simple way to implement this would be to move the `*additional_args` line above the `'-p', prompt'` lines here:

https://github.com/fdw/rofimoji/blob/main/src/picker/selector.py#L44-L65

That way users could override the keybindings with the `--rofi-args` option, e.g. `rofimoji '-kb-custom-11 Control+c'`

**Comment by fdw** [comment]
I like the idea a lot, thank you!

While your suggestion is quite easy, I'd like to consider if there are other, more obvious ways to define custom keybindings. Unfortunately, I don't have the time I'd like for `rofimoji` at the moment, but I'll see what I can do.

**Comment by fdw** [comment]
I've added something. In the end, I wanted to have explicit parameters for this, even though it's a bit more complex.
However, I don't want anyone to have to look at the code to see if its `-kb-custom-11` or `-kb-custom-12` they need, and I also think this is less inviting to mistakes.

Please try it out and report back 🙂

**Comment by DMBuce** [comment]
Works great, thanks for taking the time to add this feature! I appreciate it.
