### ISSUE TITLE
Crash when selecting an emoji in print mode with rofi

### ISSUE THREAD

**Issue by qdii** [fdw/rofimoji#85]
Problem: rofimoji crashes after selecting an emoji, when `action` is `print`

rofimoji version 5.1.0, running on Arch, with X11.

```
$ rofi -modi 'emoji:/usr/bin/rofimoji -a print' -show emoji
Traceback (most recent call last):
  File "/usr/bin/rofimoji", line 33, in <module>
    sys.exit(load_entry_point('rofimoji==5.1.0', 'console_scripts', 'rofimoji')())
  File "/usr/lib/python3.9/site-packages/picker/rofimoji.py", line 375, in main
    Rofimoji().mode_act_on_selection(chosen, int(return_value))
  File "/usr/lib/python3.9/site-packages/picker/rofimoji.py", line 185, in mode_act_on_selection
    self.save_selection_to_cache(re.match(r'^(?:\u200e(?! ))?(?P<char>.[^ ]*) .*', chosen_character).group('char'), '')
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by fdw** [comment]
Does it crash for every emoji, or just for a certain one? And is it only for `print`?

**Comment by qdii** [comment]
I’ve tried with several emojis and it crashes with them all, some I'm tempted to say all.
with `action` set as `clipboard`, it doesn't crash.

Ah I just noticed that when I use it _without_ rofi it works:

```
$ /usr/bin/rofimoji -a print
🥳
```

**Comment by fdw** [comment]
That took me longer than it should have, but `print` cannot work with the `rofi` mode: Everything `rofimoji` prints to `stdout` is taken as a choice for `rofi`. So when you select any emoji and press enter, you get a new `rofi` window with just that emoji. This is precisely the `print` action from `rofimoji`. So, after you select it again, rofimoji doesn't now what to do with that thing.

If possible, I'd suggest to use another mode. In general, `print` is for very special use-cases, where you embed `rofimoji` into some other, automated workflow.

**Comment by qdii** [comment]
Ah nice catch! That makes sense!
