### ISSUE TITLE
Packaged for Fedora 🎉

### ISSUE THREAD

**Issue by major** [fdw/rofimoji#87]
No bugs to report here, but I just wanted to let you know I've packaged rofimoji in Fedora:

* https://bodhi.fedoraproject.org/updates/FEDORA-2021-86c956b384

**Comment by fdw** [comment]
Oh gods, thank you so much! This is honestly very cool and humbling! 😊
Feel free to add the package to the readme, if you want!

Is there anything I can do to support this?
For example, I've looked through the packaging bug, and you wrote
> Perhaps rofimoji should be a bit smarter to detect which system is running.

Do you have concrete ideas how to improve the process? I do want it to choose the right stuff automatically.

**Comment by major** [comment]
@fdw Of course! I have one X11 + i3wm machine and another Wayland + sway machine. I find that rofi is used by default by rofimoji on both machines, but wofi seems to work better when wayland is active. Would there be a way for rofimoji to know *"hey, I'm on wayland, let's prefer wofi if it's here"*?

**Comment by major** [comment]
FWIW, here's what works well for me:

* **X11:** `rofimoji --action clipboard`
* **Wayland:** `rofimoji --selector wofi --action print`

If I don't use `--selector wofi` on Wayland, I end up with rofi and I have a difficult time actually selecting emojis. The focus isn't on rofi, so you can't quickly use the keyboard to select an emoji like you can under X11. Does that help at all?

**Comment by fdw** [comment]
> Would there be a way for rofimoji to know "hey, I'm on wayland, let's prefer wofi if it's here"?

First, the code is currently in a way that each selector checks if it can run, but the order of the checks (that is, the preferences) are random/defined by Python.
`rofi` is chosen when it is installed, `wofi` if it is installed and `WAYLAND_DISPLAY` is set.

So if you're on Wayland but have `rofi` installed, it could be chosen, if it checked first. On the one hand, `rofi` offers more features and so is a good choice if it is sensibly available. I guess it boils down to: How likely are you to be on Wayland, have `rofi` installed but prefer `wofi`?

**Comment by major** [comment]
I can certainly see where this becomes difficult. 🤦🏻‍♂️

**Comment by fdw** [comment]
I think I'll leave it as is until we have a better idea 🙂
