### ISSUE TITLE
Inserting flags results in AttributeError

### ISSUE THREAD

**Issue by dev-zero** [fdw/rofimoji#89]
When selecting a country flag nothing is typed, running `rofimoji` from the command line gives:

```console
$ rofimoji
Traceback (most recent call last):
  File "/usr/bin/rofimoji", line 33, in <module>
    sys.exit(load_entry_point('rofimoji==5.1.0', 'console_scripts', 'rofimoji')())
  File "/usr/lib/python3.9/site-packages/picker/rofimoji.py", line 369, in main
    Rofimoji().standalone()
  File "/usr/lib/python3.9/site-packages/picker/rofimoji.py", line 167, in standalone
    characters = self.process_chosen_characters(stdout.splitlines())
  File "/usr/lib/python3.9/site-packages/picker/rofimoji.py", line 262, in process_chosen_characters
    processed_characters = ''.join(
  File "/usr/lib/python3.9/site-packages/picker/rofimoji.py", line 263, in <genexpr>
    self.add_skin_tone(re.match(r'^(?:\u200e(?! ))?(?P<char>.[^ ]*) .*', character).group('char'))
AttributeError: 'NoneType' object has no attribute 'group'
```

This is on Wayland with Sway and Wofi.

**Comment by fdw** [comment]
Okay, this is interesting. How did you install `rofimoji`, and which version is it (I guess 5.1.0)?
Which files do you show? Just the default `emojis`, or anything different?
Is it all flags, or just a subset?

**Comment by dev-zero** [comment]
I used the Arch community package which gives me v5.1.0(-2):
```console
$ rofimoji --version
rofimoji 5.1.0
$ wofi --version
v1.2.4
```

I am using the default files, no configuration and I am simply running `rofimoji` from the command line for testing.

After some more testing the behaviour seems even stranger: it is not related to the class of emojis (despite the example here being with a flag again, I've tried also with `fondue` and others) but seems quiet random. Here I started `rofimoji` 3 times, always entered `switz` then hit enter:

```console
$ rofimoji
Traceback (most recent call last):
  File "/usr/bin/rofimoji", line 33, in <module>
    sys.exit(load_entry_point('rofimoji==5.1.0', 'console_scripts', 'rofimoji')())
  File "/usr/lib/python3.9/site-packages/picker/rofimoji.py", line 369, in main
    Rofimoji().standalone()
  File "/usr/lib/python3.9/site-packages/picker/rofimoji.py", line 167, in standalone
    characters = self.process_chosen_characters(stdout.splitlines())
  File "/usr/lib/python3.9/site-packages/picker/rofimoji.py", line 262, in process_chosen_characters
    processed_characters = ''.join(
  File "/usr/lib/python3.9/site-packages/picker/rofimoji.py", line 263, in <genexpr>
    self.add_skin_tone(re.match(r'^(?:\u200e(?! ))?(?P<char>.[^ ]*) .*', character).group('char'))
AttributeError: 'NoneType' object has no attribute 'group'
$ rofimoji
🇨%
$ rofimoji  (NOTE: cleared terminal line here, but emoji was correctly typed)
Traceback (most recent call last):
  File "/usr/bin/rofimoji", line 33, in <module>
    sys.exit(load_entry_point('rofimoji==5.1.0', 'console_scripts', 'rofimoji')())
  File "/usr/lib/python3.9/site-packages/picker/rofimoji.py", line 369, in main
    Rofimoji().standalone()
  File "/usr/lib/python3.9/site-packages/picker/rofimoji.py", line 167, in standalone
    characters = self.process_chosen_characters(stdout.splitlines())
  File "/usr/lib/python3.9/site-packages/picker/rofimoji.py", line 262, in process_chosen_characters
    processed_characters = ''.join(
  File "/usr/lib/python3.9/site-packages/picker/rofimoji.py", line 263, in <genexpr>
    self.add_skin_tone(re.match(r'^(?:\u200e(?! ))?(?P<char>.[^ ]*) .*', character).group('char'))
AttributeError: 'NoneType' object has no attribute 'group'
$ rofimoji
🇨🇭%
$ 🇨🇭
```

From what I can observe so far I am unable to trigger the error when selecting an emoji by cursor, only when typing and directly hitting enter to chose the selection. When selecting with a cursor I get an additional weird character (see above) in the stdout/stderr of rofimoji.

**Comment by s3lph** [comment]
Can reproduce. Also noticed that the issue does not occur when using with `--skin-tone neutral` (though I assume the affected code path is not used at all when using this option)

**Comment by fdw** [comment]
@s3lph I assume you're also on Wayland with `wofi`, right? Because I cannot reproduce this with `rofi` on X.

Could you help me debug this some more? If I push some code to a certain branch, would it be possible to run that and post the output?

**Comment by s3lph** [comment]
> @s3lph I assume you're also on Wayland with `wofi`, right?

Yes
> Could you help me debug this some more? If I push some code to a certain branch, would it be possible to run that and post the output?

Sure, can do

**Comment by fdw** [comment]
> Sure, can do

Thank you! I installed sway and wofi and was originally able to reproduce, but as soon as I added some code for debugging, it just worked 🤨
I've pushed a branch called `test-wofi`. Please install from there, let it run on the cli and if you get the error, please paste the output.

Thanks again!

**Comment by s3lph** [comment]
Ok, I think I've got it: If you search ONLY and not navigate at least once using Up/Down/PgUp/PgDn, the resulting chosen_caracters is only the entered text, even though a search entry is highlighted.

Searching for `facep`, then pressing Down/Up followed by Return:
```
['🤦 person facepalming <small>(disbelief, exasperation, face, palm)</small>']
```

Searching for `scien` (scientist emoji becomes highlighted, immediately followed by Return:
```
['scien']
Traceback (most recent call last):
  File "/usr/bin/rofimoji", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/picker/rofimoji.py", line 443, in main
    Rofimoji().standalone()
  File "/usr/lib/python3.9/site-packages/picker/rofimoji.py", line 236, in standalone
    characters = self.process_chosen_characters(stdout.splitlines())
  File "/usr/lib/python3.9/site-packages/picker/rofimoji.py", line 333, in process_chosen_characters
    processed_characters = ''.join(
  File "/usr/lib/python3.9/site-packages/picker/rofimoji.py", line 334, in <genexpr>
    self.add_skin_tone(re.match(r'^(?:\u200e(?! ))?(?P<char>.[^ ]*) .*', character).group('char'))
AttributeError: 'NoneType' object has no attribute 'group'
```

The issue does not seem to occur if the search result is already at the top of the list before searching (aka the most recently or most often used emoji, or however the recents file works), this may explain why its so inconsistently reproducible. That's why I used a different emoji the second time, the issue wasn't reprocible with the facepalm anymore.

**Comment by fdw** [comment]
Wow, thank you very much for that!

The bad news is that I don't think I can do anything about this. It looks like a bug in wofi.

**Comment by s3lph** [comment]
I think I found the issue:

https://github.com/fdw/rofimoji/tree/845cd440e830e971e2d93cbecb99779a73533779/src/picker/selector.py#L142
```python
if recent_characters:
    parameters.extend(['-mesg', recent_characters])
```

This seems to be copy/pasted over from the rofi implementation. Now with rofi `-mesg` is one option. With wofi, these are four options, out of which `-e` is a feature that causes exactly the behavior we're seeing here:

```man
-e, --exec-search
      Activiating a search with enter will execute the search not the first result.
```

**Comment by fdw** [comment]
🙏

Thank you very much, that sounds like the problem. Now I'm left wondering why that code is in there, as I knew that `wofi` can't display an additional message. I would just remove it. Or, if you want, you can open a PR for that and I'll merge it 🙂
