### ISSUE TITLE
[feature request] Add aliases to emojis

### ISSUE THREAD

**Issue by micgro42** [fdw/rofimoji#9]
It would be nice to have aliases available for the emojis. Thus I could also type `wizard` when looking for mage. Or dog might also surface paw prints 🐾 and an eggplant might also be found when searching for aubergine.

https://emojipedia.org/mage/

**Comment by fdw** [comment]
I completely agree, but I have unfortunately no idea where to get this data from - and it's a bit much to maintain it myself ;)
If you have any idea, please share :)

**Comment by micgro42** [comment]
GitHub maintains a ruby gem of emojis that includes a json with aliases and tags: https://github.com/github/gemoji/blob/master/db/emoji.json

**Comment by fdw** [comment]
Interesting, thanks :)
However, I'm not sure if I want to depend on some file in another repo...

Seeing as they're also parsing the official Unicode list and maintain the aliases manually, I wonder whether this could be split out as a community effort.

**Comment by fdw** [comment]
Unfortunately, they don't want to split the definitions into a separate repo (see https://github.com/github/gemoji/issues/162). Thus, the options are:
* Leave it as is without aliases
* Depend on a file in a different repo
* Maintain my own definitions

Out of them, I think 3 would be the best one, but also the most effort. Maybe I'll get around to doing this, but probably not that soon. If you want to have a go at it, feel free!

**Comment by nimobeeren** [comment]
As far as the official source of this alias data, [this](https://www.unicode.org/cldr/charts/latest/annotations/index.html) seems legit. The unicode standard calls them "annotations", and they are part of the CLDR project.

The raw data is available in a GitHub [repo](https://github.com/unicode-org/cldr/blob/master/common/annotations/en.xml) maintained by the Unicode organisation.

**Comment by fdw** [comment]
Apparently, I'm on a roll and implemented this, based on the very helpful link to the Unicode annotations from @nimobeeren. Thanks for that!

**Comment by micgro42** [comment]
Yay! 🙌
I look forward to the next release :D
