### ISSUE TITLE
Emoji does not render in selector

### ISSUE THREAD

**Issue by hukacode** [fdw/rofimoji#93]
* What does rofimoji show instead of the emojis? Can you please share a screenshot (`Alt+Shift+s** in rofimoji)
![image](https://user-images.githubusercontent.com/3462200/123115582-69b4a380-d46a-11eb-97e8-40041fd6baff.png)

* What do other apps like Firefox/Chrome/your text editor show instead of emojis?
After I select some emoji (press Enter), it is displayed.

* Which emoji fonts do you have installed?
/usr/share/fonts/noto/NotoColorEmoji.ttf: Noto Color Emoji:style=Regular

* Are the emoji fonts set in your font config?
Yes, I just got this issue recently. It was normal in the past.

* Which versions of rofimoji and pango are installed?
rofimoji: rofimoji 5.2.0

**Comment by fdw** [comment]
Yes, that is definitely a fonts issue.

> Yes, I just got this issue recently. It was normal in the past.

This makes me wonder what exactly changed. Do you know?

Also, can you check the output of `fc-match emoji`?

**Comment by fdw** [comment]
Also, you can check out some ideas from this old issue: #13

**Comment by hukacode** [comment]
Hi @fdw 

I replace the `font.conf` follow your comment here https://github.com/fdw/rofimoji/issues/13#issuecomment-507173111
Then it worked.

Thank you for your time and efforts son this great app.

**Comment by fdw** [comment]
Thank you for your kind words :)
