### ISSUE TITLE
Option "no-frecency" not working in the config file

### ISSUE THREAD

**Issue by felipejoribeiro** [fdw/rofimoji#96]
The "no-frecency = True" option do not work. Atempts  in running the application with this option result i the following error message:

```
rofimoji: error: unrecognized arguments: --no-frecency=True
```

**Comment by fdw** [comment]
This is a new feature that's not yet in any release. Which version of `rofimoji` are you using?

**Comment by felipejoribeiro** [comment]
i'm running rofimoji 5.2.0

**Comment by fdw** [comment]
Yes, frecency is a feature that will come with 5.3.0.

**Comment by felipejoribeiro** [comment]
Okk. Thank you! I will wait patiently. Keep the great work.
If you need some help with anything i would be glad to help.
This application helped me alot.

**Comment by fdw** [comment]
Hey, thanks for these kind words! 🙂 It's really good to see that my work is helpful for others.
