### ISSUE TITLE
frecency file is not updated on Alt+n insertions

### ISSUE THREAD

**Issue by larslue** [fdw/rofimoji#97]
Hi, I just checked out 5.3.0-SNAPSHOT including the "frecency" changes, and noticed that the frecency file is not updated on Alt+n insertions.

Example:

```
$ cat ~/.local/share/rofimoji/frecency
1 ⭐
1 😁
```

Inserting the same characters again with Alt+1 does not alter the file. Inserting the character again by searching for it updates the file:

```
$ cat ~/.local/share/rofimoji/frecency
2 ⭐
1 😁
```

Further, I couldn't find documentation on how to show the most frequently used characters, instead of the most recently used characters.

The command line argument `--display-recents` doesn't work for me, if this pull request happens to be related https://github.com/fdw/rofimoji/pull/78

```
$ rofimoji -a clipboard --display-recents bar
rofimoji: error: unrecognized arguments: --display-recents bar
```

Additionally, and possibly off-topic: Why did you name it frecency, rather than frequency, as the file is simply counting the number of times a character was inserted?

**Comment by fdw** [comment]
Hi 🙂

> I [...] noticed that the frecency file is not updated on Alt+n insertions.

That's right, and it did it on purpose - which doesn't mean that we can't discuss that decision ;)

**Comment by larslue** [comment]
Thank you for the extensive comment.

In this case, I have probably misunderstood the feature. The Alt+n selection continues to be sorted by recency, while the list is newly sorted by (frequency, recency)

In short:

![image](https://user-images.githubusercontent.com/16062128/126524438-7c604d0e-3f8b-49e5-be01-ef12a2180e18.png)

In this case, the Alt+n is not an issue for me. Still, I would expect an emoji would bubble up to the beginning of the list when it's inserted with Alt+n.

![image](https://user-images.githubusercontent.com/16062128/126525249-13daf7dd-dd0b-4528-929b-56290f01efd9.png)

**Comment by fdw** [comment]
> Still, I would expect an emoji would bubble up to the beginning of the list when it's inserted with Alt+n.

That does sound sensible to me. I've just changed the behavior 🙂

**Comment by larslue** [comment]
Thanks a lot, now it does work as expected! 🌟

**Comment by fdw** [comment]
You're welcome 🙂
